- backend/src/main/kotlin/xyz/elitese/ehrenamtskarte/database/repos/AcceptingStoresRepository.kt
Closes #124 .
An example query with ```searchText="ab" && categorieIds=[0,1,2]```
Before Optimization (local query time 1701.19 ms):
```sql
SELECT acceptingstores.id, acceptingstores."name", acceptingstores.description, acceptingstores."contactId", acceptingstores."categoryId"
FROM acceptingstores
WHERE
((LOWER(acceptingstores."name") LIKE '%ab%') OR (LOWER(acceptingstores.description) LIKE '%ab%') OR EXISTS (SELECT physicalstores.id, physicalstores.coordinates, physicalstores."addressId", physicalstores."storeId" FROM physicalstores WHERE (physicalstores."storeId" = acceptingstores.id) AND EXISTS (SELECT addresses.id, addresses.street, addresses."postalCode", addresses."location", addresses."countryCode" FROM addresses WHERE ((addresses.id = physicalstores."addressId") AND …
```
> 124: Optimize Search Query

- .circleci/config.yml
- .idea/ehrenamtskarte.iml
- .idea/misc.xml
- .idea/runConfigurations/Run_Flutter__prod__.xml
- .idea/runConfigurations/Run_Flutter__staging_.xml
- administration/administration.iml
- backend/build.gradle.kts
- backend/gradle.properties
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/database/Database.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/WebService.kt
- docker-compose.staging.yml
- docker/reverse_proxy/nginx-development.conf
- docker/reverse_proxy/nginx-staging.conf
- docker/reverse_proxy/www/map.html
- docker/reverse_proxy/www/style.json
- docs/staging-setup.md
- frontend/lib/main_prod.dart
- frontend/lib/main_staging.dart
- scripts/backend_deb.sh
- scripts/eak-backend.service
- scripts/pack_deb.sh
Does not close issue #227 yet, but is a working intermediate step and prevents all other PRs from getting red.
Builds a basic .deb package containing the built backend and a systemd service file for starting it.
> #227 build basic backend deb package

- frontend/lib/application/card_type_step.dart
- frontend/lib/application/entitlement_type_blue.dart
- frontend/lib/application/entitlement_type_gold.dart
- frontend/lib/application/personal_data_step.dart
- fixed radio button color not primary color
- fixed gold entitlement type options too close to each other
- default to datepicker text input for birth date because I think it's easier to type your own birthdate than manually navigating to the correct year, month and day in the date picker
> Application form improvements

- .cirrus.yml
This should fix the failing tests. On the long term, we should of course update to the latest version.
> Constrain pipeline to Flutter 2.0.6

- frontend/.fvm/fvm_config.json
- frontend/.gitignore
- frontend/README.md
- frontend/pubspec.lock
- frontend/pubspec.yaml
I have noticed after upgrading to the latest flutter version, that our project is not able to `flutter pub get` anymore. It seems the problem is an upgrade of dependencies inside the upgraded dart sdk.
I thought this might be a good time, to pin the flutter version used in the project with [FVM](https://fvm.app)
> #360: Use Flutter version 2.0.6

- .circleci/config.yml
- scripts/pack_deb.sh
This PR extends the package build script, so that a configuration file can be passed that will be added to the [conffiles control file](https://manpages.debian.org/testing/dpkg-dev/deb-conffiles.5.en.html).
This is used for the martin configuration file, so that changes to that file are not overwritten when updating the package. If both the package maintainers file and the local file have changed, an error is shown.
> fix martin config getting overwritten

- frontend/lib/intro_slides/intro_screen.dart
- frontend/lib/intro_slides/location_request_button.dart
- frontend/lib/location/determine_position.dart
previously button was static and always asking for location permission although permission was already given in a previous version of the app.
closes #374
> #374 check if location permission is granted in intro slides

- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/logging.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/Map.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/Sanitize.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/types/AcceptingStore.kt
> Sanitize street and house numbers

- backend/src/main/kotlin/app/ehrenamtskarte/backend/EntryPoint.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/constants.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/DataImporter.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/LbeDataImporter.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/DownloadLbe.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/FilterLbe.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/MapFromLbe.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/SanitizeAddress.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/SanitizeGeocode.kt
Follow up on #468. Renames pipeline steps to include `Lbe` and splits the `Map` step into `MapFromLbe` and `SanitizeAddress`.
> Split and rename pipeline steps

- frontend/lib/themes.dart
Fixes #438 
Wasn't sure about a good highlight color to use so I just picked one already used.
> Text selector not visible

- administration/src/components/generation/GenerationController.tsx
- administration/src/components/generation/PdfFactory.ts
- administration/src/exception.ts
This PR adds two things
* Suggestion: A new result type which is in my opinion way better than throwing exceptions 
* Code for checking glyphs
I would like to refactor the web frontend soon with the Result type
> Check if glyphs are available

- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/FilterDuplicates.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/FilterLbe.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/MapFromLbe.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/PostSanitizeFilter.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/SanitizeAddress.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/SanitizeGeocode.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/Store.kt
This was a request by the supervisor of my Praxismodul :grinning:
> Add documentation

- frontend/android/app/src/main/AndroidManifest.xml
- frontend/graphql_queries/regions/get_regions.graphql
- frontend/graphql_queries/regions/get_regions_by_id.graphql
- frontend/graphql_queries/stores/accepting_store_by_id.graphql
- frontend/graphql_queries/stores/accepting_store_summary_by_id.graphql
- frontend/graphql_queries/stores/accepting_stores_search.graphql
- frontend/graphql_queries/verification/card_verification_by_hash.graphql
- frontend/lib/configuration/configuration.dart
- frontend/lib/graphql/graphql_api.graphql.dart
- frontend/lib/graphql/graphql_api.graphql.g.dart
- frontend/lib/identification/card_detail_view/card_detail_view.dart
- frontend/lib/main_local.dart
- frontend/lib/main_prod.dart
- frontend/lib/main_staging.dart
- frontend/lib/map/preview/accepting_store_preview.dart
- frontend/lib/search/results_loader.dart
- frontend/lib/store_widgets/detail/detail_page.dart
- frontend/lib/verification/dialogs/positive_verification_result_dialog.dart
- frontend/lib/verification/query_server_verification.dart
- frontend/lib/verification/verification_qr_scanner_page.dart
> 555: Update GraphQL Api

- .circleci/config.yml
Fixes: 
```
dpkg-deb: error: archive '/var/lib/local-apt-repository/../../..//srv/local-apt-repository/eak-backend_0.8607-1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
output = subprocess.check_output(command)
File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/lib/local-apt-repository/../../..//srv/local-apt-repository/eak-backend_0.8607-1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' …
```
> Target debian when packaging and building martin

- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/constants.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/schema/RegionsQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/AcceptingStoreQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardQueryService.kt
- specs/backend-api.graphql
> Remove deprecated APIs

- administration/public/index.html
- administration/src/App.tsx
- administration/src/KeepAliveToken.tsx
- administration/src/components/AppToaster.ts
- administration/src/components/AppToaster.tsx
- administration/src/components/applications/ApplicationsOverview.tsx
- administration/src/components/applications/JsonFieldView.tsx
- administration/src/components/auth/Login.tsx
- administration/src/components/generation/GenerationController.tsx
- administration/src/index.tsx
- docs/development-setup.md
To complete the upgrade to react 18, we need to use createRoot from react-dom/client.
Moreover, I had to adjust the creation of the AppToaster, which uses the deprecated old API.
> Upgrade to React 18

- administration/src/AuthProvider.tsx
- administration/src/KeepAliveToken.tsx
- administration/src/components/auth/Login.tsx
We still keep the concept, that the user is logged out after 1 hours.
However, 3 minutes before that, the user is prompted to enter the password to extend his log-in-time.
If he is not able to enter the password within 3 minutes, he is logged out automatically.
Closes #492
> 492: Keep user logged in after closing tab

- .circleci/config.yml
- scripts/pack_deb.sh
Styles are since a while hosted on maps.tuerantuer.org
fixes #587
> MERGE ME NEXT: Remove styles

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Setup.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
> Rename EakApplications to Applications

- frontend/android/app/buildConfigs.gradle
Set correct project dir (rootDir) for gradle exec
> Set project rootDir for gradle

- frontend/build-configs/bayern/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/types.ts
> 608: Add applicationUrl to build config

- frontend/lib/map/map/map.dart
- frontend/lib/map/map_page.dart
This PR fixes two bugs:
1. If the user selects selects a store on the map, the map **should** move the camera to center the store and show a larger symbol on top. However, it didn't.
2. If the user has given location permission to the app on Android, the app crashes on startup (especially with the release build).
The first bug was fixed by querying the coordinates from the geometry of the map feature. 
I fixed the second bug by removing a previous hack (which seems to be unnecessary by now). This luckily resolved the crash.
Please test this thoroughly:
With and without location permissions enabled, check whether all animations look correct (and that the animation does not stop early which was the reason for the hack).
> Fix map bugs

- frontend/build-configs/.prettierrc
- frontend/build-configs/bayern/index.ts
- frontend/build-configs/bayern/localization.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/nuernberg/localization.ts
- frontend/build-configs/types.ts
- frontend/lib/about/about_page.dart
- frontend/lib/about/texts.dart
- frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
- frontend/lib/identification/card_detail_view/more_actions_dialog.dart
- frontend/lib/identification/identification_page.dart
- frontend/lib/identification/no_card_view.dart
- frontend/lib/identification/verification_workflow/dialogs/positive_verification_result_dialog.dart
- frontend/lib/identification/verification_workflow/dialogs/verification_info_dialog.dart
- frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
> Whitelabel ausweisen tab

- administration/src/cards/CardBlueprint.ts
- administration/src/cards/PdfFactory.ts
- administration/src/cards/activation.ts
- administration/src/components/cards/CreateCardsController.tsx
- administration/src/project-configs/bayern/config.ts
- administration/src/project-configs/getProjectConfig.ts
- administration/src/project-configs/nuernberg/config.ts
- administration/src/project-configs/showcase/config.ts
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/database/repos/CardRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/service/CardVerifier.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/types/CardGenerationModel.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/types/CardVerificationModel.kt
- specs/backend-api.graphql
I did not create a separate mutation/query for the static cards, so far as the only difference is the presence of the totp secret. 
Would it make sense to verify the project in the backend, so that you cannot create a static qrcode for bayern? I personally think that static qrcodes should be treated as a feature, that can be turned on for every project. But am not sure how to verify this correctly in the backend.
> 675: Support static qr codes in backend and administration

- .circleci/config.yml
- administration/src/project-configs/nuernberg/dataPrivacyBase.tsx
We use 2 dart version in the CI. This can cause Can't load Kernel binary: Invalid kernel binary format version when installing global plugins using one version and then using it from the other.
This PR also fixes a typo in the privacy policy.
> Fix "Can't load Kernel binary: Invalid kernel binary format version" for protoc

- frontend/ios/Podfile
- frontend/ios/Podfile.lock
- frontend/lib/configuration/settings_model.dart
- frontend/lib/identification/identification_page.dart
- frontend/lib/identification/qr_code_scanner/qr_code_camera_permission_dialog.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
I'm not sure if this separate package for permissions is really needed
I used a state to check if permission was requested before because android permission is `denied` initially and by choosing explicit deny on permission dialog.
Let me know if that way is fine
- if camera access is not granted -> request permission before opening QRCode Scanner
- if camera access was denied showDialog
resolves https://github.com/digitalfabrik/entitlementcard/issues/770
> 770: Add camera permission check

- frontend/lib/identification/verification_workflow/dialogs/positive_verification_result_dialog.dart
- frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
- frontend/lib/themes.dart
resolves https://github.com/digitalfabrik/entitlementcard/issues/753
> 753: add checkbox for static qr code verification

- docs/development-setup.md
- docs/production-setup.md
Also resolves #646. I don't see any reason to not document the workflow. However, I still kept the note that we make the releases ourselves.
> Document release workflow

- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ViewAdministratorsQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/database/Database.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/WebService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/database/repos/RegionsRepository.kt
This PR fixes a few small annoyances
* Order regions and admins in queries
* Start webservice only once all handlers are configured (helpful if their configuration errors)
* Log all SQL queries in dev mode
> Small backend fixes

- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Setup.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ManageUsersMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
Expression indices are [not yet supported in exposed](https://github.com/JetBrains/Exposed/issues/895) therefore the manual creation. If you have any idea where to create the index or whether there might be a better solution let me no.
> 826: Modify index on email to be lowercased

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/applicationGraphQLParams.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/dataloader/ApplicationDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/view/ApplicationView.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Setup.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/authGraphQLParams.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/dataloader/AdministratorDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/database/sortByKeys.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLParams.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/NamedDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/projects/database/Setup.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/dataloader/RegionDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/regionsGraphQLParams.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/repos/AcceptingStoresRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/AcceptingStoreDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/AddressDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/CategoryDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/ContactDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/PhysicalStoreByStoreIdLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/PhysicalStoreDataLoader.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/types/AcceptingStore.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/types/PhysicalStore.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/storesGraphQLParams.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/verificationGraphQLParams.kt
Closes #851. Refactoring of the data loaders:
* Disable caching on all data loaders
* Make registering and naming of data loaders less boilerplaty and less error-prone
* Avoid name conflicts of data loaders
* Make them more type safe
Also, I rewrote the data loader for physicalStoreByStoreIdLoader which makes the `searchAcceptingStores` GraphQL query  a lot faster: Instead of ~20 single SQL queries (one for each store) we now make a single SQL query.
> 851: Refactor data loaders and disable caching

- .circleci/config.yml
GitHub leaked their private SSH key. Hence, we have to swap out their public key in our CI pipeline with their new one.
See https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/ for further reference.
> Swap out Github SSH key

- administration/src/application-verification/VerificationController.tsx
- administration/src/components/applications/ApplicationApplicantController.tsx
resolves https://github.com/digitalfabrik/entitlementcard/issues/867
> 867: Verification view material ui

- administration/src/application-verification/VerificationController.tsx
- administration/src/components/applications/ApplicationApplicantView.tsx
- administration/src/components/applications/ApplicationsOverview.tsx
- administration/src/components/applications/JsonFieldView.tsx
resolves https://github.com/digitalfabrik/entitlementcard/issues/862
> 862: Attachment cannot be downloaded

- administration/src/components/applications/ApplicationApplicantController.tsx
- administration/src/components/errors/getMessageFromApolloError.tsx
May be improved in the overall error handling PR.
> 910: Separate error message for network errors

- administration/application_commit.sh
This fixes the issue that the application version would not increase any longer after the recent refactor in #912.
I added another check to the bash script verifying that the application source folder still exists.
> Fix application version

- administration/src/bp-modules/ButtonBar.tsx
- administration/src/bp-modules/cards/CreateCardsForm.tsx
- administration/src/bp-modules/regions/RegionOverview.tsx
relates to https://github.com/digitalfabrik/entitlementcard/pull/950/files/ee46329fac04c913684962adc6834b4354b344fb#r1175259189
> Move button bar to bottom

- .circleci/config.yml
Workaround to this issue
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129
Seems like the dependency of `openjdk` isn't fixed yet
> fix java certificates

- administration/src/mui-modules/application/ApplyController.tsx
- administration/src/mui-modules/application/forms/ApplicationForm.tsx
- administration/src/mui-modules/application/forms/StepSendForm.tsx
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/Application.kt
- specs/backend-api.graphql
> 970: Add checkbox for email usage in application form

- frontend/.fvm/fvm_config.json
- frontend/analysis_options.yaml
- frontend/android/build.gradle
- frontend/lib/identification/card_detail_view/verification_code_view.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
This was a much more boring upgrade than I thought :D
It needs testing on iOS though.
Here's a changelog: 
https://docs.flutter.dev/release/whats-new#10-may-2023-google-io-2023-310-release
> Upgrade flutter to 3.10

- docs/production-setup.md
- frontend/pubspec.yaml
Updated bash command for build config in docs since a minus was missing and quotes are not needed. This resulted for me to a fallback to bayern. Had to add a new build to android for sozialpass so i also updated latest build version
> Release-3.1.0-fixes

- administration/src/cards/CardBlueprint.ts
- frontend/lib/identification/id_card/card_content.dart
resolves #1014 
-limit is 30 to also ensure that names with wide chars can be displayed on the digital card and printed card in a single row
-added fitbox widget to ensure rendering of the fullname content
> 1014: Limit fullname length

- .circleci/config.yml
- frontend/lib/about/dev_settings_view.dart
- frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
- frontend/lib/identification/card_detail_view/verification_code_view.dart
- frontend/lib/identification/qr_content_parser.dart
- frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
- frontend/test/canonical_json_test.dart
- frontend/test/card_info_util_test.dart
The CI broke due to an update of protoc_plugin.
Please also run `dart pub global activate protoc_plugin` locally and verify if version 21 is installed (You might have to upgrade your global flutter/dart installation).
See https://pub.dev/packages/protoc_plugin/changelog#2102 for the relevant changes of protoc_plugin.
> Fix CI: Migrate constructor syntax due to protoc_plugin 21

- administration/src/bp-modules/regions/data-privacy-policy/DataPrivacyPolicy.tsx
- administration/src/mui-modules/application/forms/StepSendForm.tsx
- administration/src/project-configs/bayern/config.ts
- administration/src/project-configs/bayern/dataPrivacyBase.tsx
- administration/src/project-configs/getProjectConfig.ts
resolves #1030 
- If no region specific policy is provided show additional base text
- show additional base text for general data privacy policy (linked in app)
> 1030: Incomplete data privacy

- administration/src/bp-modules/auth/ForgotPasswordController.tsx
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
> 1051: No feedback pw reset

- frontend/lib/identification/verification_workflow/query_server_verification.dart
Apply some hardening to `queryServerVerification`.
I believe, this PR does *not* fix the recent problems with card activations, where cards could successfully be activated, but were then shown as invalid.
Related:
#1049, #1065, #1056
> Harden queryServerVerification

- frontend/lib/identification/card_detail_view/card_detail_view.dart
- frontend/lib/identification/card_detail_view/self_verify_card.dart
- frontend/lib/identification/card_detail_view/verification_code_view.dart
- frontend/lib/identification/otp_generator.dart
This PR untangles how the app determines the status of a persisted card.
It should be clearer to see what is shown in the "Ausweisen" tab.
The only functional change:
* We initiate self-verification in any status (previously, we did not self-verify if the card expired (according to local clock) or if it the backend ever responded with `invalid`). 
* Try to detect race-conditions in self-verification (possibly conflicting with activation): If the UserCode was set while doing the server request, then ignore the result.
Minor change:
* VerificationCodeView sets its own timer (instead of OTPGenerator setting it), in order to be able to cancel it in case it is being disposed. Previously, we had an error in the console, when the VerificationCodeView was unmounted.
> Untangle card status in app

- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardMutationService.kt
To avoid race conditions when activating a card (e.g. if the app somehow requests activation too often), this PR introduces DB transaction isolation for the activation transaction.
> Avoid DB race condition when activating

- frontend/lib/identification/activation_workflow/activate_code.dart
- frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
- frontend/lib/identification/activation_workflow/activation_overwrite_existing_dialog.dart
Previously, errors that happened after the user confirms overriding an existing device, were not shown to the user.
> Show error if activation with override fails

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
As always, feel free to critique the format. Not my strong point ^^
> 1074: add applicant name to verification Mail

- backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/service/CardVerifier.kt
- frontend/lib/about/dev_settings_view.dart
- frontend/lib/identification/card_detail_view/card_detail_view.dart
- frontend/lib/identification/card_detail_view/self_verify_card.dart
- frontend/lib/identification/verification_workflow/query_server_verification.dart
- frontend/lib/identification/verification_workflow/verification_qr_code_processor.dart
- specs/card.proto
This should resolve #1065, #1056, #1049
When during self-verification, the time of the device is out of sync with the sever, the device would generate a wrong otp code and, thus, the server would respond that the card is not valid. The current app-store version (<= 3.1.3) of the app had the additional problem, that if the server responded once with "invalid", the app would not try to self-verify again the next time the app launches. This was already fixed by #1071 . This means, in the current dev-version (also before this PR), if you landed in this screen, resynced your local time, and restarted the app, the error would go away.
The solution I implemented here, is to simply analyze whether the time of the local device is out of sync at the time of self-verification. If so, we show a …
> Show time out of sync error

- frontend/lib/widgets/app_bars.dart
resolves #1115 
Test with: "Museum der Stadt Augsburg " -> now works
If you use auto complete on soft keyboard the additional empty space resulted in not getting a search result
> 1115: Trim search text

- administration/package-lock.json
- administration/src/bp-modules/applications/ApplicationsOverview.tsx
- administration/src/bp-modules/applications/VerificationsView.tsx
resolves #1114 
Please properly test the sorting by creating some applications with different status.
Applications that are not fully approved or rejected will have the status "waiting" and put in the end, since they are not actionable
> 1114: Sort applications by status

- .idea/runConfigurations/Run__env_local_buildConfig_bayern_.xml
- .idea/runConfigurations/Run__env_local_buildConfig_nuernberg_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_bayern_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_bayern_floss_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_nuernberg_.xml
- docs/graphql_generation.md
The flutter run configs did have a "before" task, that was linking to a non-existing run configuration. I assume the "Select bayern" is now the "Set build config bayern" task. I fixed the linking, so the selection is correctly executed before flutter run.
> Fix run configs

- administration/src/cards/pdf/PdfQrCodeElement.ts
- administration/src/util/helper.ts
- frontend/lib/about/dev_settings_view.dart
It was not possible to add a base64 card in dev settings anymore, because the verification failed and the libraries to read the barcode didn't work properly anymore to get even a proper base64 string. so i simplified this.
- log base64 string to avoid using the additional libraries (like before) to gain the base64 string
- added missing CardVerification in dev settings
Testing:
- create a card in the druckerei, check console for base64 string
- go to "Über" -> DevSettings -> Add base64 card
Note: Some ui issues exists on ios for the multi cards slider and will be fixed in #1142 
Fixes: #1144
> 1144: Add base64 cards

- docker-compose.yml
- docker/nginx-development.conf
- docs/development-setup.md
In #1134 we realized, that some urls did not work. This should be fixed in this PR.
- add route for map and styles to our nginx server
- mount submodule to nginx output
- there shouldn't be anythin
-
Fixes: #1141
> 1141: add route for map and styles to our reverse_proxy

- frontend/build-configs/bayern/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/types.ts
- frontend/lib/app.dart
- frontend/pubs/df_build_config/lib/builder.dart
Add the available locales to the build config and use them to configure the app locales.
- Add `appLocales` to build config
- Fix builder.dart script
- Use `appLocales` to configure the app locales
None.
Fixes: #1176.
> 1176: Configure locales in build config

- backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
Changed encoding
This is an encoding problem, the mail in the screenshot is displayed in `iso 8859-1`, but we have a header saying it should be displayed in `utf8`. I opened a PR change dit to `UTF-8` as this is the correct wording, as this can fix the error for some users, see:
> The charset value should be utf-8, not any other values such as utf8. Using utf8, for example, is a common mistake, and even though it is valid nowadays as the [specifications](https://encoding.spec.whatwg.org/#names-and-labels) and browsers now alias utf8 to utf-8, that wasn’t the case in the past, so things might break in [some older browsers](https://twitter.com/jacobrossi/status/591435377291866112). The same may be true for other agents (non-browsers) that may scan/get the content and may not have the alias. …
> 1191: Fix mail content type header charset

- docs/production-setup.md
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Nuernberg.xcscheme
- frontend/ios/ScreenshotTests/ScreenshotTests.swift
- frontend/ios/fastlane/Fastfile
- frontend/ios/fastlane/README.md
I moved the commands into the fastfile, as it is pretty hard to write out the whole command you proposed in the command line. Besides that I have had issues with active support (which I didn't commit), didn't you have the same problem? -> https://github.com/fastlane/fastlane/issues/21585
- move commands into fastfile
- pass launch arguments when testing from xcode
> 1029: proposal empty map auto screenshot

- administration/public/index.html
After an update on some browsers the new version of the druckerei will not be loaded from the server but the old version from the cache. This issue leads to error with api interactions.
- add cache control headers in meta tags that avoid caching of the index.html file
Fixes: #1226
> 1226: Fix duckerei cache

- frontend/ios/Runner/Info.plist
- frontend/ios/Runner/de.lproj/InfoPlist.strings
- frontend/ios/Runner/en.lproj/InfoPlist.strings
Our app was rejected since apple couldn't find the permission strings, since they were moved to localizations. 
- readd the strings in info.plist
- added missing `NSLocationAlwaysAndWhenInUseUsageDescription` to localizations and info.plist
Fixes: #1238
> 1238: Missing permission strings

- .circleci/config.yml
- .circleci/src/commands/check_circleci_config.yml
- .circleci/src/commands/install_fvm.yml
- .circleci/src/jobs/check_frontend.yml
The whole `check_frontend` job was running from working directory `frontend`. While the `build_android` and `build_ios` were not. This lead to the result that the cached file at `frontend/.fvm
- remove working directory from `check_frontend` job
- add working directory to the commands instead
> Fix cache path for fvm

- administration/src/mui-modules/application/forms/ApplicationForm.tsx
- administration/src/mui-modules/application/forms/BlueCardEntitlementForm.tsx
- administration/src/mui-modules/application/forms/GoldenCardEntitlementForm.tsx
- administration/src/mui-modules/application/forms/OrganizationForm.tsx
- administration/src/mui-modules/application/forms/StepRequirementsForm.tsx
- administration/src/mui-modules/application/forms/WorkAtDepartmentEntitlementForm.tsx
- administration/src/mui-modules/application/forms/WorkAtOrganizationForm.tsx
- administration/src/mui-modules/application/forms/WorkAtOrganizationsEntitlementForm.tsx
Currently it is possible to set yourself as contact person in an application. The user should be informed that this will very likely not lead to a successful application.
- added hint about who this person is supposed to be
- added hint when applicant names are identical to the contact persons name
Fixes: #1210
> 1210: Add hint to contact person of organization

- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/MigrationsRegistry.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0008_IncreaseAdministratorEmailLength.kt
Apparently emails can be longer than 100 characters. An email length of 254 characters can be considered the maximum length, therefore this PR increases the allowed length to 254.
- add migration to increase allowed email length
Fixes: #850
> 850: Increase allowed email length to 254

- frontend/lib/identification/user_code_store.dart
We are facing some not reproducible issue on android devices that the user data (stored cards) can't be read from secure storage after app restart. This relies on an issue from `flutter secure storage`
https://github.com/mogol/flutter_secure_storage/issues/653
Some devs report that a fake read could solve this issue.
- add a fake read for android devices
- add a second read for android devices that may contain the user data
- report error to sentry if first read is null but second read contains data to collect more information
- the initialization of the cards may be a bit slower for android but it shouldn't be a big performance issue
related to #1265
**Note:** We have to contact users that facing the issue if it was solved by this workaround, since we can not really test it
Just test if …
> 1265: Workaround empty secure storage

- frontend/lib/about/language_change.dart
- frontend/lib/app.dart
The fix of not recreating the router causes some issue for the language change -> duplicated bottomTabsMenu
When activating card with deep link and not confirming the intro slides and reopening the app, there is the home route missing when the user then accepts intro slides
- fix language change
- add missing home route
> fix-recreating-home-proposal

- frontend/lib/about/language_change.dart
- frontend/lib/app.dart
After #179, the whole app tree was constantly recreated if the location feature was enabled.
This was because GoRouter recreated the whole app tree every time any the settingsmodel notified about changes. 
Do not recreate GoRouter after every Settings change. It seems this is the recommended way to use GoRouter.
(see this sample usage https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/main.dart)
Hopefully none, except for fixing the bug.
> Construct GoRouter only once to prevent tree recreation on settings change

- frontend/analysis_options.yaml
- frontend/lib/about/about_page.dart
- frontend/lib/about/content_tile.dart
- frontend/lib/about/language_change.dart
- frontend/lib/app.dart
- frontend/lib/identification/card_detail_view/card_detail_view.dart
- frontend/lib/identification/card_detail_view/self_verify_card.dart
- frontend/lib/intro_slides/intro_screen.dart
- frontend/lib/map/preview/accepting_store_preview_card.dart
- frontend/lib/search/results_loader.dart
- frontend/lib/store_widgets/accepting_store_summary.dart
- frontend/lib/store_widgets/detail/detail_content.dart
- frontend/lib/store_widgets/detail/detail_page.dart
Subroutes are pushed to the root navigator.
Subroutes are pushed to the root navigator.
When navigating to map from the detail page of a search result, we have to first pop the detail page from the navigator stack and then navigate to the map tab.
None
Fixes: #1170 #1288
> 1170: Use root navigator when pushing subroutes

- .circleci/config.yml
- .circleci/src/@common.yml
- .circleci/src/jobs/deliver_ios.yml
- .circleci/src/workflows/delivery_production_native.yml
- frontend/ios/fastlane/Fastfile
- version.json
Added the option to deliver to production for native app.
- added delivery_production_native workflow
- added lane for ios production delivery
- None, but I saw that on the first try, the bump_version commit started the commit workflow, when restarting it was not triggered. I guess this happend, because the commit message was not propery sent to circleci, see here: https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4493/workflows/57ba0bbf-7c35-46a1-b3ec-8ba7b86c6d46
Please let me know if you see this happening in the future again.
Fixes: #1155
> 1155: Add deliver-production-ios

- .circleci/config.yml
- .circleci/src/commands/notify.yml
- .circleci/src/commands/restore_ruby_cache.yml
- .circleci/src/jobs/build_android.yml
- .circleci/src/jobs/bump_version.yml
- .circleci/src/jobs/deliver_android.yml
- .circleci/src/workflows/delivery_beta_native.yml
- version.json
delivery is failing due to wrong permissions while installing the gems, see here: https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4572/workflows/75290bc2-3332-49b1-8762-74c3ea5ab9e9/jobs/35497
- fixed the duplication of messages sent
- added missing check step to beta delivery workflow
- fixed bundler update issue
- updated android images
> Fix cicd install bundler

- administration/src/util/getDeepLinkFromQrCode.test.ts
Activation codes in this test depend on timestamp, because the default expiry date will be calculated. So different runtime generate different activationCodes. This shouldn't be the case
- add fix timestamp for tests
Fixes: #1346
> 1346: Fix deep link test

- frontend/android/fastlane/Fastfile
- frontend/ios/fastlane/Fastfile
- frontend/lib/configuration/definitions.dart
The environment variable for production builds was not passed correctly to android and ios in the ci, so the environment fallback `showcase` was used instead production. That caused loading wrong stores
- remove quotes for base64 string for android
- pass the environment variable via xcargs for ios
- check uploaded artifacts in browserstack (ipa testing)
- or get the artifacts here:
[Android](https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4720/workflows/4788f1e6-f79b-4195-831b-967c36ec4123/jobs/35992/artifacts)
[iOS](https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4738/workflows/c13863ab-e88b-4a34-9188-bd5b4fefa292/jobs/36053/artifacts)
- now the correct stores should be displayed in SearchList and Map
> Fix-ci-environment-variable

- administration/src/errors/getMessageFromApolloError.tsx
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/PasswordCrypto.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/MigrationsRegistry.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0009_HashPasswordResetKey.kt
To ensure that the password reset keys are safe even if the DB is somehow exposed we only want to store the hash of the password reset key.
- migrate db 1) change datatype to bytea 2) change column name
- add hashing logic
- change referential equality check on project to structural equality check this actually fixes #821 
- correctly handle runtime errors in frontend
- existing passwordResetKeys become invalid
Fixes: #887
> 887: Hash PasswordResetKey

- frontend/assets/l10n/app_de.json
- frontend/assets/l10n/app_en.json
- frontend/assets/nuernberg/l10n/override_de.json
- frontend/assets/nuernberg/l10n/override_en.json
Adjust reactivation message if the card has already been activated on another device.
Currently the user might be confused if the card was activated on another device and then deleted and activated on a new device that a message will be shown that the card will be deactivated on the other device.
I have adjusted the message suggested in the task to keep it a couple words shorter, but feel free to object.
- No?
Fixes: #1266
> 1266: Adjust reactivation message card active on another device

- docs/migrations.md
If for any reason a db migration update does not run successfully after debian package installation (within post install), a devops user might want to run the database migration manually on the server.
- add section in migration docs with migration commands for server
> Update migration docs

- .circleci/config.yml
- .circleci/src/jobs/build_android.yml
- frontend/android/app/build.gradle
- frontend/android/build.gradle
- frontend/android/settings.gradle
* Applied migration according to [Flutter's migration guide](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) 
* Removed some dependencies workaround
* Removed a path lookup workaround
Hopefully none.
Fixes: #1354
> 1354: Migrate to declarative gradle plugins

- frontend/lib/widgets/app_bars.dart
Bugfix:
After using the search function (and displaying the on-screen keyboard), when you subsequently open the location on the map, the on-screen keyboard opens again, even though there is no input field
- set the onTapOutside property for the search text box to hide the keyboard (i.e. to remove the focus from the field) when the user clicks outside the text box
- add the keyboardToggler variable and update _onSearchPressed() to preserve the current behavior of the search button - toggling the keyboard on click
- no?
Fixes: #1396
> 1396: Hide keyboard when navigating to the map

- .circleci/config.yml
- .circleci/src/jobs/notify_release.yml
- .circleci/src/workflows/delivery_beta_native.yml
As a dev i want that after successful delivery a github release with release notes will be created.
- add `notify_release` job to create a release, generate release notes, upload artifacts and send mattermost notification to release channel
https://github.com/digitalfabrik/app-toolbelt/pull/13 (merged)
resolves #1232, resolves #1319, resolves #1331, resolves #1165
1. Important deactivate delivery tasks in `deliver_beta_native`(!!!)
2. Push your commit
3. 
```sh
curl -X POST https://circleci.com/api/v2/project/github/digitalfabrik/entitlementcard/pipeline \
--header "Circle-Token: <"your token">" \
--header "content-type: application/json" \
--data '{"branch":"1232-create-github-release", "parameters":{"run_delivery_beta_native":true, "run_commit":false}}'
```
> 1232: Create github release

- .circleci/config.yml
- .circleci/src/@common.yml
- .circleci/src/jobs/build_martin.yml
- .circleci/src/jobs/check_health_backend.yml
- .circleci/src/jobs/pack_administration.yml
- .circleci/src/jobs/pack_backend.yml
- .circleci/src/jobs/pack_martin.yml
- .circleci/src/jobs/pack_meta.yml
- .circleci/src/workflows/commit_main.yml
By now, we deploy the backend on debian 12 (bookworm).
This upgrades the debian CI images to v12.
This should fix problems related to extremely old Node versions on these builds.
- Likely none, except that CI warnings & errors related to old Node versions should be resolved.
Fixes: #1361
> Upgrade debian images to bookworm

- frontend/lib/search/filter_bar.dart
Add the "Others" category button to the filter bar.
- return the Others category in the filter bar
Actually this category was removed intentionally in this PR https://github.com/digitalfabrik/entitlementcard/pull/709/files
But I didn't find why?
Maybe it shouldn't be displayed in Nürnberg, but then we could remove it from the config probably?
Fixes: #1388
> 1388: Add the Others category to the filter bar in the app

- .circleci/config.yml
- .circleci/src/commands/install_dart_mac.yml
Looks like protobuf flutter plugin fails with new dart version which was not locked for mac.
- lock dart version @3.3.1
Check working pipeline here: https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/5331/workflows/20653ee9-54d6-48c7-b255-e6b03bd5c71d
> Fix ios build commit main

- .circleci/config.yml
- .circleci/src/jobs/notify_release.yml
To be able to restore a certain backend and administration version, we should upload the debian packages to github releases, since they debian files will be cleaned for the servers every 31 days
- add upload step to notify release
- none
Fixes: #1442
Here you can find the "test" release
https://github.com/digitalfabrik/entitlementcard/releases/tag/2024.5.0-all
> 1442: Add deb files

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/view/ApplicationView.kt
Currently a not authorized user such as applicant or verifier could add "note" into the graphl query and get private notes from the application.
- add a flag `includePrivateInformation` and only populates notes int the ApplicationView if its set to true
Fixes: #1391
> 1391: Notes only queryable by admins

- administration/src/bp-modules/cards/AddCardForm.tsx
As a service user it might be confusing if the field "Ablaufdatum" shows a particular date if gold card is selected, since gold card has an infinite lifetime
- only render "Ablaufdatum" field if "Standard" is the selected for card type
- none
Fixes: #1458
- Create a card and select "Goldkarte"
- Field Ablaufdatum should disappear
- Choose Standard and the field should appear again
> 1458: Remove endDate gold card

- administration/src/mui-modules/application-verification/ApplicationApplicantView.tsx
For bigger screens the list container jumps if "Antragsdetails" will be opened
- set a fixed width for non mobile devices to avoid container jumping
Fixes: #1459 
- Create an application
- Open the link in the received mail
- Open the collapse "Antragsdetails"
- Container should not jump
> 1459: Applicant application view width

- .circleci/config.yml
- .circleci/src/jobs/install_packages_to_server.yml
- .circleci/src/jobs/promote_to_server.yml
- .circleci/src/jobs/upload_packages_to_server.yml
- .circleci/src/workflows/deliver_beta_all.yml
- .circleci/src/workflows/deliver_beta_backend_administration.yml
- .circleci/src/workflows/deliver_production_backend_administration.yml
The installation of the backend and administration fails quite often even if the debian packages are existing on the server. This may have different reasons like racing conditions or one webhook(administration) and second webhook(backend) blocks each other because they were triggered simultaneously
- merge package installation and trigger one webhook to avoid blocking installations
- separate package upload and package installation jobs
Fixes: #1455
Relate to several salt prs: 
- https://git.tuerantuer.org/DF/salt/pulls/157 (added a apt repo rebuild to ensure that packages will be recognized directly after uploading before installation was started
- https://git.tuerantuer.org/DF/salt/pulls/158 merge the webhook
> 1455: Improve debian package installation

- administration/src/bp-modules/cards/ImportCardsController.tsx
- administration/src/bp-modules/cards/hooks/useCardGenerator.ts
Execution of export csv cards and print cards with bulk data fails
- adjust function executions
- none
-
Fixes: #1468
1. Go to "Mehrere Karten erstellen"
2. use csv import file from `administration/resources/cards/sample-nbg.csv`
3. click csv export
4. repeat step 1. and 2. and click QR-Codes drucken
> 1468: Bulk csv card export fails

- .circleci/config.yml
- .circleci/src/jobs/notify_release.yml
- .circleci/src/jobs/pack_administration.yml
- .circleci/src/jobs/upload_packages_to_server.yml
- .circleci/src/workflows/deliver_beta_all.yml
- version.json
Latest release with missing bavaria administration artifacts.
Fixed some ci issues to get the delivery work
- renamed some steps because of wrong naming
- commented out non working notify step https://github.com/digitalfabrik/entitlementcard/issues/1453
Notes: We have different version numbers for native artifacts (2024.5.5) and backend (2024.5.6) since backend job failed at first run. Couldn't delete native store version versions to redeploy all, since they are in review. But it think its okay. But versions are based on the same tag
> release-2024.5.3

- administration/src/mui-modules/application-verification/ApplicationVerificationController.tsx
If an application gets withdrawed by the applicant, the verifier doesn't get a proper message
- show a proper message to the verifier
Fixes: #1479
1. Create an application and set your mail address also for verification
2. Withdraw the application
3. Open the link in the verification mail
4. Check proper message
> 1479: Missing withdrawed message

- administration/src/mui-modules/application/forms/StepCardTypeForm.tsx
The link for the requirements of the EC changed
- replace the link
Fixes: #1465
1. http://localhost:3000/beantragen
2. type in personal data and go next
3. Check the link above "Blaue Ehrenamtskarte" -> "hier einsehen" for the requirements
> 1465: Replace requirements link

- administration/src/bp-modules/applications/ApplicationsOverview.tsx
For a service user the description of an empty list per status is not clear because the description is general
- add the particular status to the description and title for empty list message
Fixes: #1470 
- Go to applications
- Click on a status that is empty
- check description and title of the message
> 1470: Misleading wording empty list

- administration/src/Router.tsx
- administration/src/bp-modules/cards/hooks/useCardGenerator.ts
- administration/src/mui-modules/activation/ActivationPage.tsx
- administration/src/mui-modules/activation/components/ActivationPageContent.tsx
- administration/src/project-configs/bayern/activationText.tsx
- administration/src/project-configs/getProjectConfig.ts
- administration/src/util/__tests__/getCustomDeepLinkFromActivationCode.test.ts
- administration/src/util/getCustomDeepLinkFromActivationCode.ts
- administration/src/util/getDeepLinkFromQrCode.test.ts
- administration/src/util/getDeepLinkFromQrCode.ts
- frontend/build-configs/constants/index.ts
Since we have some issues with associated domains on some android device, it may be useful to also provide a custom scheme link to the user for card activation since it works without domain association
- add button for card activation with custom scheme deeplink
- fixed some linting issues
- none 
Fixes: #1485 
1. Create a card
2. copy the pdf on your device
3. click on the qr code on the pdf and open with a browser
4. replace the domain with your local network ip to be able to load the local state f.e.
```js
http://192.168.161.22:3000//activation/code#CkkKHwoPQW5kcmVhcyBGaXNjaGVyEO2jARoICgIICSICCAASEAkhZfDlmmOKpEMx5vIR3aoaFKFbplTzRz55MY6S4wA16chnLn5J/
```
5. Switch to "Ehrenamtskarte" (will only appear in dev environment)
6. Click on "Karte aktivieren"
> 1485: Improve activation route

- .circleci/config.yml
- .circleci/src/jobs/build_administration.yml
- .circleci/src/jobs/build_android.yml
- .circleci/src/jobs/build_ios.yml
- .circleci/src/jobs/bump_version.yml
- .circleci/src/jobs/check.yml
- .circleci/src/jobs/check_administration.yml
- .circleci/src/jobs/check_backend.yml
- .circleci/src/jobs/check_frontend.yml
- .circleci/src/jobs/deliver_ios.yml
- .circleci/src/jobs/install_packages_to_server.yml
- .circleci/src/jobs/notify_release.yml
- .circleci/src/jobs/pack_backend.yml
- .circleci/src/jobs/pack_meta.yml
- .circleci/src/jobs/promote_android.yml
- .circleci/src/jobs/promote_ios.yml
- .circleci/src/jobs/promote_to_server.yml
- .circleci/src/jobs/upload_packages_to_server.yml
Notification fails due to node versions that have issues
- adjust node versions to lts
- use node img instead of base, since the nodejs version were not working
- add missing notifications to jobs
- the images of node may be little bit larger than base but don't require installation of additional packages and are fixed to a particular version
Fixes: #1453
> 1453: Fix failing notify

- administration/src/project-configs/bayern/activationText.tsx
Typo in the card activation text
Fixes: #1482
> 1482: Fix typo in the card activation text

- administration/src/bp-modules/applications/ApplicationCard.tsx
As a user i want to get a quick indicator if a note was set
- add note icon to the application header if a note was set
-none
Fixes: #1489
1. Go to applications and create a note. Icon should be displayed
> 1489: Note icon application header

- backend/build.gradle.kts
Update jetty version (required for javalin) to fix memory leaks
- update jetty version to 11.0.21
- adjust protobuf image for mac 
- didn't face any
Fixes: #1509
> 1509: Fix memory leaks

- frontend/lib/identification/qr_code_scanner/qr_code_scanner.dart
- frontend/lib/main.dart
- frontend/lib/util/android_utils.dart
Some android cameras don't recognize barcodes due to some upstream android camera issues.
This seem to be related to the defaultCamera resolution each device uses
https://github.com/juliansteenbakker/mobile_scanner/issues/698
Its not that easy to detect which cameras may be issued to not apply this on all android devices.
- provide a fixed camera resolution for specific android models
- aspect ratio is not correct. so we can discuss if this is good enough, because it looks ugly
- i played around with the values but didn't find a working solution with correct aspect ratio so far 
Related: #1507 
I'm not sure if we should set the cameraResolution to all android devices because it looks ugly. But its also difficult to maintain particular models, so let me know what you think. We could keep …
> 1507: Mobile scanner does not recognize barcodes

- backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
Since password reset is not behind a login and can be triggered easily, this api interactions should be protected
- write to log if an unknown user(mail address) requests a password reset mail
- write to log if an reset password fails
- this log will be checked from fail2ban (check related pr)
- no
Fixes: #663
related to : https://git.tuerantuer.org/DF/salt/pulls/187
> 663: Protect pw reset mail

- .circleci/config.yml
- .circleci/src/@common.yml
- .circleci/src/jobs/promote_github_release.yml
- .circleci/src/workflows/promote_all.yml
We want to promote native and backend, administration with one single workflow
- add promote all workflow
- add job to remove github pre release flag
- none
Fixes: #1446 
Fixes: #1392
I've already triggered this job partly to remove the github pre release flag and it worked :)
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/5600/workflows/7ea5be90-4f68-4b66-b403-2177e8972e51
> 1446: Promote all

- administration/src/bp-modules/statistics/constants/index.ts
Region header is missing in the CSV export of cards statictics
Add 'region' to the mapping of statistics keys
no?
Fixes: #1508
> 1508: Add region header to the CSV export of cards statistics

- administration/src/graphql/applications/getApplication.graphql
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
- specs/backend-api.graphql
We are facing some issues that we get a lot of server logs that no applications where found.
To be able to better investigate why this happens we log the `accessKeys` of the applicants and verifiers that cannot get applications.
- add logger if `application == null` that logs ip address and accessKey
- some small refactoring to clarify which accessKeys will be passed
- none
relates: #1223 
1. Create an application that needs an organization to verify
2. Open the verification and the application link and check that everything is still working
3. Remove some characters of the `accessKey` in the links and check the backend log
> 1223: Log no applications

- backend/build.gradle.kts
- backend/src/test/kotlin/app/ehrenamtskarte/backend/IntegrationTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/userdata/UserImportTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/util/CsvGenerator.kt
- backend/src/test/resources/config.test.yml
Add integration tests for user import endpoint.
Blocked by https://github.com/digitalfabrik/entitlementcard/pull/1536
- implement UserImportTest
Shouldn't be any
Fixes: #1532
> 1416: Tests for the user import endpoint 

- .circleci/config.yml
- .circleci/src/jobs/build_backend.yml
This should potentially fix failing build_backend job
Can only be verified once merged, since build_backend doesn't run on PR
Failing CI:
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/5968/workflows/cf3ad231-f60d-4bd4-966f-07013e4991d1/jobs/42825
> Fix failing build_backend job

- administration/@types/normalize-strings.d.ts
- administration/package.json
- administration/src/mui-modules/application/forms/OrganizationForm.tsx
- administration/src/util/__tests__/normalizeString.test.ts
- administration/src/util/normalizeString.ts
- administration/tsconfig.json
- package-lock.json
Make name comparison more robust.
- Use normalize-strings
- Trim whitespaces before comparing
- Remove special characters before comparing
None.
Fixes: #1381.
> 1381: Make name comparison more robust

- backend/build.gradle.kts
- backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardQueryService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/config/BackendConfiguration.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/matomo/Matomo.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/AcceptingStoreQueryService.kt
- backend/src/main/resources/config/config.yml
- backend/src/test/resources/config.test.yml
We create many MatomoTrackers which require manual cleanup/closing. Since some version the tracker cleans up after itself automatically when created in a try-catch resource construct: https://github.com/matomo-org/matomo-java-tracker/issues/215#issuecomment-1986844774
- Upgrade matomo dependency
- make sure we only have a single tracker
Fixes #1544
> Fix thread exhaustion/leak

- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0014_CreateUserEntitlementsTable.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/userdata/database/Schema.kt
Fix warning
`[main] INFO Exposed - Index on table 'UserEntitlements' differs only in name: in db unique_userhash_regionid -> in mapping unique_userHash_regionId`
- Rename the unique_userhash_regionid index to lowercase
I assume it's okay just to update the existing migration, as it hasn't been released yet
> 1416: Rename the unique_userhash_regionid index to lowercase

- frontend/lib/favorites/favorites_loader.dart
- frontend/lib/search/results_loader.dart
Sometimes the following exception can be seen in the log, most likely right after the application starts:
```
_Exception: Exception: A PagingController was used after being disposed.
Once you have called dispose() on a PagingController, it can no longer be used.
If you’re using a Future, it probably completed after the disposal of the owning widget.
Make sure dispose() has not been called yet before using the PagingController.
File "paging_controller.dart", line 133, in PagingController._debugAssertNotDisposed.<fn>
File "paging_controller.dart", line 142, in PagingController._debugAssertNotDisposed
File "paging_controller.dart", line 168, in PagingController.notifyStatusListeners
File "paging_controller.dart", line 94, in PagingController.value=
File "paging_controller.dart", line 69, in …
```
> 🥳 1312: Fix exception when PageController was used after being disposed

- backend/src/main/kotlin/app/ehrenamtskarte/backend/config/BackendConfiguration.kt
Allows to parse configs that include unkown (potentially future) properties. Previouisly starting the server failed if you parse an unknown value.
None
> Allow unknown config properties

- frontend/ios/fastlane/Fastfile
The ios promotion requires release notes.  With #1503 the metadata was restructured but the metadata path not added. So still the default path `./metadata` was used and an error occurred during promotion
- add a build config depended metadata path
- none
no testing
Fixes: #1543
> 1543: Fix metadata promotion

- .circleci/config.yml
- .circleci/src/jobs/check_backend.yml
Add store_test_results step to check_backend job for debug purposes.
It allows to see how many tests have been run and if there were failed tests, a summary of them will also be shown here.
no
n/a
n/a
> Add store_test_results step to check_backend job

- frontend/assets/l10n/app_de.json
- frontend/assets/l10n/app_en.json
- frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
Some users seem to scan the static verification code (physical pass) for activation instead of the activation code.
First there was an unknown error report.
To be able to get proper error information we send the information to Sentry. Since we identified the issue the error reporting to Sentry can be removed
- improve the error message to indicate the user what should be scanned
- remove sending error reports to sentry, since this is an intended error and displays error information to to the user
- none
1. Create a card for nuernberg
2. add screenshot of the static qr code to the emulator/ or scan it with real device
3. try to activate the card and check error message
Fixes: #1286
> 1286: Improve error message activation

- backend/build.gradle.kts
- backend/src/test/kotlin/app/ehrenamtskarte/backend/GraphqlApiTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/CreateCardFromSelfServiceTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/CreateCardsByCardInfosTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestAdministrators.kt
- Add TestAdministrators enum to create admins and auth tokens in tests
- Add tests for createCardsByCardInfos mutation where authorization token is used as an example
no, just tests
n/a
n/a
> Tests for createCardsByCardInfos mutation + authorization setup

- backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/userdata/KoblenzUser.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/Argon2IdHasherTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/CanonicalJsonTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/CreateCardFromSelfServiceTest.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/ExampleUser.kt
- docs/CreateKoblenzHash.md
Exclude fullName field from user hashing
> Koblenz-Pass News: "Aktenzeichen in der Kombination mit Geburtsdatum sind datenschutzrechtlich vereinbar. Die Übertragung des Aktenzeichen und des Geburtsdatums sind möglich."
- Adjust Argon2IdHasher, docs, tests
Card can be issued under any name
1. Import user entitlements via POST http://localhost:8000/users/import
Include CSV file as a form-data:
```
regionKey,userHash,startDate,endDate,revoked
07111,"$argon2id$v=19$m=19456,t=2,p=1$cr3lP9IMUKNz4BLfPGlAOHq1z98G5/2tTbhDIko35tY",01.01.2024,01.01.2025,false
```
The above hash **does not contain** a name of the user
2. Send graphql request to create card:
```
mutation CreateCardFromSelfService {
createCardFromSelfService(
project: "koblenz.sozialpass.app"
encodedCardInfo: …
```
> 1628: Exclude fullName field from user hashing

- frontend/lib/graphql/configured_graphql_provider.dart
- frontend/lib/home/home_page.dart
The graphql provider was twice in the widget tree: The `App` and `HomePage` widgets both "rendered" the graphql provider.
I removed the one at `HomePage` as the one in `App` was further up the tree. 
Likely none. Maybe caching works better now.... Not sure what other consequences there are when there are two graphql providers in place.
General smoke test ? :D
> Remove duplicate graphql provider

- frontend/ios/Podfile.lock
- frontend/pubspec.lock
- frontend/pubspec.yaml
Due to this issue we should lock the version to 9.0.0
https://github.com/mogol/flutter_secure_storage/issues/762
- lock version 9.0.0
- hopefully none
-
1. Activate card and test if the data will be kept in storage after app restart
I tested this with ios 17.5 und 18.0
> Downgrade secure storage

- .gitignore
- .idea/codeStyles/Project.xml
- frontend/.idea/frontend.iml
I frequently have changes to my intellij setting files which is rather annoying as I sometimes commit them accidentally.
- Use code style from prettierrc
- Add inspection profiles to gitignore
None.
None.
Fixes: None.
> Ignore intellij settings and use prettier code style

- administration/src/bp-modules/components/AppStoreLinks.tsx
- administration/src/bp-modules/self-service/CardSelfServiceInformation.tsx
- administration/src/bp-modules/self-service/constants/selfServiceStepInfo.tsx
- frontend/build-configs/bayern/index.ts
- frontend/build-configs/koblenz/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/types.ts
For the download instructions of the koblenz pass self service we need store links. in #1707 we may also create a separate app download route and need also the urls for the other projects
- add store urls for all project in buildConfig
- extract `AppStoreLinks` component to make it reusable for #1707 
-none
1. Ensure `npm i` ran on root folder to have new buildConfig variables
2. Start koblenz pass go to /erstellen and create a pass.
3. Go to next and check that the store links are properly set. Note that for ios the app is not visible until first production release
Fixes: #1647
> 1647: Add store links

- administration/src/errors/DefaultErrorMap.tsx
Updated the error message according to the [design](https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=778-663&t=7BmRX1tjzp8daWp1-1) 
no
1. Open administration --> login as a koblenz project admin --> go to settings --> create token
2. Try to import users using curl or Postman
`curl -H "Authorization: Bearer <my_token>" -F file=@import_testdata_local.csv http://0.0.0.0:8000/users/import`
**CSV content:**
```
regionKey,userHash,startDate,endDate,revoked
07111,"$argon2id$v=19$m=19456,t=2,p=1$cr3lP9IMUKNz4BLfPGlAOHq1z98G5/2tTbhDIko35tY",01.01.2024,01.01.2025,true
```
3. Go to http://localhost:3000/ and select Koblenz
4. Go to http://localhost:3000/erstellen, create a card with a birthday 10.06.2003 and a reference number 123K
--> **check the new error message** …
> 1415: Update the error message when user entitlement is expired or revoked

- administration/src/project-configs/showcase/config.ts
- administration/src/util/__tests__/getCustomDeepLinkFromActivationCode.test.ts
- administration/src/util/getCustomDeepLinkFromActivationCode.ts
- administration/src/util/getCustomDeepLinkFromQrCode.ts
- docs/deep-linking.md
- frontend/build-configs/bayern/index.ts
- frontend/build-configs/constants/index.ts
- frontend/build-configs/koblenz/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/ios/Runner/Info.plist
Currently we use the same custom scheme for the deeplinks of all our apps `berechtigungskarte://`
If a user has more than just one of these apps installed it is not clear which app should be opened by clicking a deeplink.
While in android there would be a app selection (which is also should be avoided), in ios there will be just one of the apps proposed to open the link. Therefore each app should have its own custom scheme to prevent that
- add a custom scheme for each project
- adjust the info.plist file for ios to use this value from the buildConfig instead of a hardcoded string
- adjust tests
- adjust custom deeplink creation to use the correct scheme
- none, since currently custom deeplinks only exist on the /activation route of the administration
- Create a card. Copy the code from …
> 1688: Fix custom scheme deeplinks

- frontend/analysis_options.yaml
- frontend/lib/about/backend_switch_dialog.dart
- frontend/lib/about/language_change.dart
- frontend/lib/activation/deeplink_activation.dart
- frontend/lib/home/home_page.dart
- frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
- frontend/lib/identification/identification_page.dart
- frontend/lib/identification/qr_code_scanner/qr_code_scanner.dart
- frontend/lib/identification/util/activate_card.dart
- frontend/lib/identification/verification_workflow/dialogs/verification_info_dialog.dart
- frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
- frontend/lib/identification/verification_workflow/verification_workflow.dart
- frontend/lib/intro_slides/location_request_button.dart
- frontend/lib/location/determine_position.dart
- frontend/lib/map/location_button.dart
- frontend/lib/map/map/map.dart
- frontend/lib/search/results_loader.dart
- frontend/lib/search/sorting_button.dart
- frontend/lib/store_widgets/detail/detail_app_bar.dart
- frontend/lib/store_widgets/removed_store_content.dart
Enable the linting rule ["use_build_context_synchronously"](https://dart.dev/tools/linter-rules/use_build_context_synchronously) and fix errors in our code.
This PR sprinkles the codebase with some `mounted`  guards that check whether the widget is still mounted and the BuildContext can still be used, e.g. for displaying a dialog, etc.
I noticed that the linting rule is not perfect, ie. it has both false positives and false negatives. However, as we have had some error reports due to incorrect usage of context, I think it's still a good idea to activate it.
* Sorting by location in map & search
* Card Activation & verification
* Deeplink card activation
Fixes: #435, #1725, #1726, #1729, #1730, #1731, #1732, #1733, #1734, #1735
> 435: Use build context synchronously.

- frontend/lib/about/dev_settings_view.dart
- frontend/lib/activation/deeplink_activation.dart
- frontend/lib/identification/card_detail_view/card_detail_view.dart
- frontend/lib/identification/card_detail_view/self_verify_card.dart
- frontend/lib/identification/user_code_model.dart
- frontend/lib/identification/user_code_store.dart
- frontend/lib/identification/util/activate_card.dart
- frontend/lib/util/read_write_lock.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
* Use Mutex to ensure that FlutterSecureStorage is only ever used by a single operation at once (I personally believe, that this will not fix the existing issues; it's still a good idea to be certain)
* self_verify_card.dart:
- I removed some code paths that were unreachable.
- I added userCodeModel as an attribute so that it outlives the context. (should likely fix https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/4478/)
* UserCodeModel now looks for existing cards by comparing card info AND pepper (as opposed to only card info). This should only be relevant if a card with the exact same information is issued twice (e.g. if the first one was accidentally revoked or did not work or ...)
I could have probably split these into three separate PRs... Let me know if I should do …
> Fortify Code Store

- backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/dataloader/PhysicalStoreByStoreIdLoader.kt
The `searchAcceptingStoresInProject` query never returns physical stores.
Therefore, the functionality to show the distance (or location) of an accepting store, that is already implemented in Flutter in the search page, never worked (or rather stopped working at some point).
Fix the data loader responsible for querying the physical store given a store.
The functionality will kick in once the backend is deployed without needing to release the app again.
Check out the search page.
Fixes: #1283
> 1283: Fix physical store by store loader

- administration/package.json
- administration/src/util/__tests__/normalizeString.test.ts
- administration/src/util/normalizeString.ts
- package-lock.json
Remove normalize-strings dependency.
Very similar functionality can be achieved by using `String.normalize` ([caniuse.com](https://caniuse.com/?search=String.normalize)) without this dependency.
Possibly slightly different outcomes of `normalizeName` and `normalizeString`. However, it's only used for comparing two names, so it should not be critical.
For enthuastic testers: test the organization form in the application form.
> Remove normalize-strings dependency

- frontend/assets/l10n/app_de.json
- frontend/assets/l10n/app_en.json
The interpolation of the number of licenses is currently broken.
Fix it by using the correct interpolation syntax.
None
Open the licenses page
> Fix number of licenses

- docs/verein360-enpoint.md
Added documentation we can sent to verein360. As soon as this PR is approved I will send this documentation to Verein360. The deadline for this is end of november.
you can call the endpoint as specified and check if this works as expected.
Fixes: #1750
> 1750: Endpoint specification for verein360

- frontend/build-configs/bayern/index.ts
- frontend/build-configs/koblenz/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/types.ts
- frontend/lib/identification/identification_page.dart
Currently we use one particular applicationUrl (Pass beantragen) for the app. For better testing on staging and local we should provide this depending on environment.
- add different applicationUrls
- open application process depending environment
1. Open "Beantragen"  on local, staging and production environment
Fixes: #1792
> 1792: Application url depends environment

- administration/src/cards/extensions/BirthdayExtension.tsx
- administration/src/util/PlainDate.ts
Fix birthday date picker.
- Remove redundant and erroneous conversion `toLocaleDateString` 
- None.
Select a birthday at `localhost:3000/erstellen` from the date picker.
Fixes: #1795
> 1795: Fix birthday date picker

- frontend/lib/main.dart
Get rid of the exception when starting the Koblenz app
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/koblenz/l10n/override_en.json".
The asset does not exist or has empty data.
```
- override translations only if the asset exists
- no?
Start the Koblenz app, check there is no exception in log
Fixes: #1710
> 1710: Handle empty language overrides

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationHandler.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/MigrationsRegistry.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0025_AddSourceFieldToApplicationVerifications.kt
- backend/src/test/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationServiceTest.kt
Application verifications get source set for verein360 applications
- adjusted database to have column "automaticSource"
- refined check for incoming applications
None, maybe affecting normal application creation process
create new application with one or more organizations. Check for correct error messages if isAlreadyVerified differs. Check if one or all are true, the applicationVerifications table column automaticSource is set properly to VEREIN360
Feel free to test the complete feature in this PR: https://github.com/digitalfabrik/entitlementcard/pull/1811
Fixes: #1791
> 1791: Create application verifications automatically for verein360 applications

- administration/src/cards/Card.test.ts
- administration/src/util/helper.ts
Since some names may contain "-", "." or "'" we have to allow some certain special chars.
If you find anything thats missing here please let me know
- remove some special chars from the not allowed regex pattern
- add some missing special characters
- added some additional tests
- none
- Create a koblenz card and test some names that include allowed special chars
- Test some names like "Dr. Vorname Nachname" , "Mac O'Connor", "Hans-Wilhelm Müller-Wohlfahrt"
Fixes: #1817
> 1817: Allow certain special characters

- administration/src/cards/Card.test.ts
- administration/src/cards/Card.ts
Since in some countries exists name with only one digit, we should allow them
- reduce minimum name character count to `>0`
- none
1. Go to /erstellen
2. Type in name with just one single character like "A F" or "Karla K"
3. Name shouldn't be marked as invalid anymore
Fixes: #1827
> 1827: Surnames single digit

- administration/src/mui-modules/application/primitive-inputs/CheckboxForm.tsx
The "*" symbol is duplicated for the mandatory checkboxes on the application form.
The asterisks are aligned differently and have different colors if a validation error occurred.
I think it looks strange.
Remove duplicated "*" from the label
Not sure why it was done this way, maybe I'm missing something?
I have tested the form in Chrome and Firefox
check eak application form
n/a
> Remove duplicated * on the application form

- frontend/build-configs/bayern/index.ts
- frontend/build-configs/koblenz/index.ts
- frontend/build-configs/nuernberg/index.ts
- frontend/build-configs/types.ts
- frontend/lib/map/map/attribution_dialog.dart
Currently the map attribution was hardcoded (with LBE Bayern) for all whitelabels but the map attribution depends on the particular project.
- show different map attribution per project
- none
- Open the map attribution for each project (left corner of map)
- Check the text and if the link is working
Fixes: #1821
> 1821: Fix wrong map attribution

- frontend/lib/activation/deeplink_activation.dart
- frontend/lib/app.dart
- frontend/lib/home/home_page.dart
- frontend/lib/identification/identification_page.dart
When a user activates a second card via deeplink, the app directly moves to the first card after activation. This may confuse the user
- introduce a `cardIndex` for Home route be able to initialize the identification page  (child of home route) with the particular card index
- add the card index to the route push when activating card via deeplink
Since we have to wait until the identification page widget is initialized its not possible to just execute a `moveTo` function after activating the deeplink, so i think thats the best way to do.
- don't think so, worst thing could happen to initialize at cardIndex 0
1. Activate a card via deeplink
2. Activate a second card via deeplink
3. Check the after activation the latest card will be displayed
Fixes: #1824
> 1824: Card extension jumps to old card

- frontend/lib/search/results_loader.dart
Last store item is hidden in list because its behind the sorting FAB button
- add a sized box as spacer
- none
Open search page and scroll down to last item. Check if its readable
Fixes: #1835
> 1835: Fix last store item hidden

- frontend/.gitignore
- frontend/analysis_options.yaml
- frontend/build.yaml
- frontend/graphql_queries/cards/card_activation.graphql
- frontend/graphql_queries/cards/card_verification_by_hash.graphql
- frontend/graphql_queries/regions/get_regions.graphql
- frontend/graphql_queries/regions/get_regions_by_id.graphql
- frontend/graphql_queries/stores/accepting_store_by_id.graphql
- frontend/graphql_queries/stores/accepting_store_summary_by_id.graphql
- frontend/graphql_queries/stores/accepting_stores_search.graphql
- frontend/lib/favorites/favorite_store.dart
- frontend/lib/favorites/favorites_loader.dart
- frontend/lib/identification/activation_workflow/activate_code.dart
- frontend/lib/identification/id_card/id_card_with_region_query.dart
- frontend/lib/identification/util/activate_card.dart
- frontend/lib/identification/verification_workflow/query_server_verification.dart
- frontend/lib/map/preview/accepting_store_preview.dart
- frontend/lib/search/results_loader.dart
- frontend/lib/search/search_page.dart
- frontend/lib/store_widgets/accepting_store_summary.dart
- frontend/lib/store_widgets/detail/detail_content.dart
- frontend/lib/store_widgets/detail/detail_page.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
- frontend/test/favorites/favorites_page_test.dart
Replace the discontinued artemis package with graphql_codegen.
I went with graphql_codegen, as I believe using `ferry` would require much more changes, and has an (imo) worse API.
None
Smoke test interactions with the server.
Fixes: #1352
> Replace artemis with graphql_codegen

- administration/src/bp-modules/cards/hooks/useCardGenerator.ts
- administration/src/bp-modules/user-settings/ActivityLog.ts
- administration/src/bp-modules/user-settings/ActivityLogCard.tsx
- administration/src/cards/Card.ts
- administration/src/cards/extensions/AddressFieldExtensions.ts
- administration/src/cards/extensions/BavariaCardTypeExtension.tsx
- administration/src/cards/extensions/BirthdayExtension.tsx
- administration/src/cards/extensions/EMailNotificationExtension.ts
- administration/src/cards/extensions/KoblenzReferenceNumberExtension.tsx
- administration/src/cards/extensions/NuernbergPassIdExtension.tsx
- administration/src/cards/extensions/RegionExtension.ts
- administration/src/cards/extensions/StartDayExtension.tsx
- administration/src/cards/extensions/extensions.tsx
- administration/src/project-configs/getProjectConfig.ts
- administration/src/project-configs/nuernberg/ActivityLogEntry.tsx
- administration/src/util/PlainDate.ts
The activity log was broken for a while due to serializing not happening properly. This introduces proper typing and serializing.
- Add `fromSerialized` and `serialize` methods to each extension and for cards
- Properly serialize activity log and use iso8601
- Old activity logs break the serializing (but this should not happen as they are only session based)
See issue.
Fixes: #1840
> 1840: Properly serialize activity log and fix it

- frontend/lib/activation/deeplink_activation.dart
Currently the wrong card index is set after activating a card from deep link. That leads to the issue that an activated card can't be deleted.
- Pass the `cardIndex` not the card amount to the route to initialize the identification page with the correct card index
- none
-
1. Run koblenz production build
2. Switch to staging environment
3. Activate a koblenz pass ("Ausweisen" -> "Beantragen" use user information from `administration/resources/selfService
4. Go to "Weitere Aktionen" and delete the card
5. Dialog should open and card can be deleted
Fixes: #1851
> 1851: Fix card deletion

- administration/src/bp-modules/applications/JsonFieldArray.tsx
- administration/src/bp-modules/applications/JsonFieldElemental.tsx
- administration/src/bp-modules/applications/JsonFieldView.tsx
- administration/src/mui-modules/application/forms/BlueCardEntitlementForm.tsx
- administration/src/mui-modules/application/forms/GoldenCardEntitlementForm.tsx
- administration/src/util/translations/de.json
Some application labels were not resolved properly
- rename i18n keys according to how they will stored in the database to be able to resolve them properly,
- adjust these keys in the form states where they will be set
- fix key of `goldenCardHonoredByMinisterPresidentEntitlement`, 
- consider parents for resolving keys for attachments, 
- fix wrong label (#1852)
- Maybe some attachment labels may be affected so please check all labels of an application card properly
1. Create applications with the different requirements, all possible for the blue card and all possible for the golden card
2. Open the application list and check if all application labels were resolved correctly, due to the `de.json`, there were some keys like `certificate` resolved wrong because the parents wasn't used …
> 1843: Missing application labels

- administration/src/bp-modules/EmailLink.tsx
- administration/src/bp-modules/applications/JsonFieldElemental.tsx
- administration/src/bp-modules/applications/VerificationsView.tsx
- administration/src/bp-modules/applications/utils/verificationHelper.ts
- administration/src/bp-modules/applications/utils/verificationHelper.tsx
The e-mail addresses should be clickable so that they do not have to be copied and pasted.
- Modifying `JsonFieldElemental` to check string if its a valid email address to show is as a `mail:to` link.
- `verificationHelper.tsx` having the regex for email verification function at `bp-modules/applications/utils`
- `JsonFieldElemental.tsx` modified.
- Create an application for a specific region
- Login with regionAdmin or regionManager of that specific region
- Check application if mail addresses are clickable
Fixes: #1755
> 1755: clickable email addresses

- administration/src/mui-modules/application/primitive-inputs/EmailForm.tsx
Entering an invalid email, e.g. "a@de", which is allowed to be set in the input text field, but cannot be sent when sending the application will give an error message that no email could be sent to the address. The application however will still be created.
- Used `isEmailValid` function from utils `bp-modules/applications/utils`
- `primitive-inputs/EmailForm.tsx`
- We could use https://www.usercheck.com api to prevent temporary emails also ... it has 1000 check per month free then when its done we can fallback to normal behavior.
1. Go to https://staging.bayern.ehrenamtskarte.app/beantragen
2. Enter all mandatory information
3. Under WEITERE ANGABEN for email address enter an invalid email, e.g. "a@de".
4. For the email of the contact person of an organization enter an invalid email, …
> 1683: Adding email validation for email forms

- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationHandler.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
As a trainer from verein360, i want to receive a confirmation mail for my application i sent for an applicatant.
Background: For verein360 not the applicant him/herself creates application but the trainer for him/her.
So the confirmation mail should not be send to the applicant but to the creator of the application in this case the trainer.
- if the application was send by verein360 and is pre verified send an e mail to the contact person/trainer of the organization.
- none
- send an application request (graphiql or postman) using a mail address as contact person that you own (to check that you receive the mail)
- Example for an graphql mutation you can find here: https://github.com/digitalfabrik/entitlementcard/pull/1863
Fixes: #1865
> 1865: Custom application created confirmation mail

- frontend/lib/identification/user_code_model.dart
This pr fixes the issue that the same card could be activated twice on the same device, even the first card is changing to an invalid state. Basically if the same card is already activated on this device, the user shouldn't be able to activate it again.
- add a deep equality check for the peppers lists ton ensure same cards are correctly identified
- none
1. Create a card for nuernberg or koblenz (where multiple cards can be activated)
2. Activate the card once. Then use the same qr code and try to activate the same card
3. There should be a message, that the card is already activated on your device
Fixes: #1850
> 1850: Fix multi card activation

- frontend/lib/main.dart
There is an error in the log when launching the Nürnberg app
```
TypeError: Null check operator used on a null value
File "singleton.dart", line 504, in LocaleSettingsExt.overrideTranslations
File "translations.g.dart", line 174, in LocaleSettings.overrideTranslations
File "main.dart", line 66, in overrideLocale
```
This also means that one of the languages was not loaded correctly and the default translation was used.
I guess it’s related to asynchronous processing.
I have added ‘await’ to the overrideLocale() call and it seems to help.
Hopefully none
- Check that the translations for each application are loaded properly (overrides are applied in the app)
- Check the language change for Nürnberg (About -> Settings -> Change language)
Fixes: #1882
> 1882: Fix translations override

- frontend/build-configs/bayern/disclaimerText.ts
- frontend/build-configs/koblenz/disclaimerText.ts
- frontend/build-configs/nuernberg/disclaimerText.ts
- frontend/lib/about/texts.dart
Follow-up for https://github.com/digitalfabrik/entitlementcard/pull/1881
I have changed other legal texts (copyright text, disclaimer text) to html to unify the approach.
Not tested on iOS, but I believe it will look the same as the publisher text.
Check the copyright and disclaimer texts in the apps:
Über -> Lizenz
Über -> Haftung, Haftungsausschluss und Impressum
N/a
> 1880: Use flutter_html for all legal texts

- administration/src/bp-modules/components/TextAreaDialog.tsx
- administration/src/bp-modules/regions/data-privacy-policy/DataPrivacyOverview.tsx
- administration/src/errors/DefaultErrorMap.ts
- administration/src/errors/GraphQlErrorMap.tsx
- administration/src/errors/getMessageFromApolloError.tsx
We have the issue that all non `GraphlBaseExceptions` will result in the same message to the user and 403 exceptions will be handled as a network error and just result in `Server nicht erreichbar`
- remove the check for `networkError` but handle all errors which are not graphql errors in a `defaultErrorMap` and check for the particular error code and send the matching error message
- if non of these error codes were found just then return 'Server nicht erreichbar', because we didn't get any response from the backend (the most probably reason i guess)
- some error messages may change or not be displayed
I'm not pretty sure how to test this on staging because, most of the errors were handled before by not showing the function like `PepperSettings` or `ApiTokenSettings``
As a dev you can …
> 1660: Handle apollo errors

- administration/src/App.tsx
- administration/src/bp-modules/AppToaster.tsx
- administration/src/bp-modules/cards/CreateCardsButtonBar.test.tsx
- administration/src/bp-modules/cards/ImportCardsInput.test.tsx
- administration/src/bp-modules/cards/hooks/useCardGenerator.test.tsx
- administration/src/bp-modules/self-service/__tests__/CardSelfServiceActivation.test.tsx
- administration/src/bp-modules/self-service/__tests__/CardSelfServiceForm.test.tsx
- administration/src/bp-modules/self-service/__tests__/CardSelfServiceInformation.test.tsx
- administration/src/bp-modules/self-service/hooks/__tests__/useCardGeneratorSelfService.test.tsx
- administration/src/bp-modules/self-service/hooks/useCardGeneratorSelfService.tsx
- administration/src/bp-modules/stores/__tests__/StoreImportResult.test.tsx
- administration/src/bp-modules/stores/__tests__/StoresButtonBar.test.tsx
- administration/src/bp-modules/stores/__tests__/StoresCSVInput.test.tsx
- administration/src/bp-modules/stores/__tests__/StoresImportAlert.test.tsx
- administration/src/bp-modules/util/ProjectSwitcher.tsx
- administration/src/project-configs/ProjectConfigContext.tsx
- administration/src/project-configs/getProjectConfig.ts
- administration/src/testing/render.tsx
- administration/src/util/getCustomDeepLinkFromQrCode.ts
Fix circular dependency to allow for use of project config in extensions (including for testing).
- Pass a project config to ProjectContextProvider instead of using getProjectConfig directly
- Adjust the tests to easily set a project config
The `setOverrideProject` has been removed as it is unsafe and should be avoided (e.g. for tests).
Everything should still work for the different projects.
Fixes: #1909
> 1909: Fix circular dependency to use of project config in extensions

- backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/service/CardActivator.kt
We have a performance issue in the staging environment.
When creating cards in bulk (Karten erstellen --> Mehrere Karten importieren), if a csv file contains 300 entries, the request processing time takes almost a minute.
If a user imports multiple large files in parallel, processing may take more than a minute, resulting in a timeout error.
97% of the processing time during the card creation is spent hashing the activation code.
I suggest reducing the hash cost to 10 (this is the default value), this will cut the query processing time in half.
Pls check out the discussion in the issue comments for more details.
The discussion there is still open, so I'm not sure if everyone agrees, but I'm opening this PR as a suggestion to move the task forward anyway.
The hashing complexity is reduced, …
> 1610: Optimize cards creation performance

- administration/src/bp-modules/stores/StoresButtonBar.tsx
Under some conditions, the following error occurred on the page of importing stores when hovering the cursor over the “Importiere Akzeptanzpartner ” button.
Adding a condition to disable the tooltip helps avoid the error
no?
Please follow the steps from the issue description
Fixes: #1918
> 1918: Fix ResizeObserver loop error

- administration/src/mui-modules/application/forms/JuleicaEntitlementForm.tsx
Fix a key for a translation.
-
-
- Start the administration frontend: `npm run start` in `/administration`
- Visit http://localhost:3000/beantragen
- In step 2, choose "Blaue Ehrenamtskarte", (for easier stepping, comment line 120 in `administration/src/mui-modules/application/SteppedSubForms.tsx`
- In step 4, see the attachment title
Fixes: #1958
> 1958: Fix the key for JuLeiCa card attachment title in the application form

- frontend/android/app/build.gradle
- frontend/android/app/buildConfigs.gradle
- frontend/android/app/src/main/AndroidManifest.xml
Allow parallel installation of development and production builds on android.
- Add `.development` to application id for development builds
- Add ` DEV` suffix to app name for development builds
- Previous installations will not be used anymore, so e.g. cards have to be added again
Install both a production build from the store and a development build in parallel.
Fixes: N/A
> Allow parallel installation of development and production builds

- administration/src/util/__tests__/getDeepLinkFromQrCode.test.ts
- administration/src/util/getDeepLinkFromQrCode.ts
- administration/src/util/helper.ts
Since we build the same bundles for staging and production on web, we have to distinguish between staging and production on the basis of the domain. Thats why we currently send reports also for staging.
- add a missing hostname check
- unify function names
- none
N/A
Fixes: #1935
> 1935: Sentry sends reports for staging

- administration/src/bp-modules/cards/AddCardsController.tsx
- administration/src/bp-modules/cards/AddCardsForm.tsx
- administration/src/bp-modules/cards/ImportCardsController.tsx
- administration/src/bp-modules/cards/hooks/useCardGenerator.test.tsx
- administration/src/bp-modules/cards/hooks/useCardGenerator.ts
- administration/src/bp-modules/cards/hooks/useSendCardConfirmationMails.ts
- administration/src/bp-modules/self-service/CardSelfServiceActivation.tsx
- administration/src/bp-modules/self-service/CardSelfServiceView.tsx
- administration/src/bp-modules/self-service/__tests__/CardSelfServiceActivation.test.tsx
- administration/src/bp-modules/self-service/constants/selfServiceStepInfo.tsx
- administration/src/bp-modules/self-service/hooks/__tests__/useCardGeneratorSelfService.test.tsx
- administration/src/bp-modules/self-service/hooks/useCardGeneratorSelfService.tsx
- administration/src/bp-modules/util/cardGenerationError.tsx
- administration/src/cards/CsvFactory.ts
- administration/src/cards/PdfFactory.ts
- administration/src/cards/__tests__/CsvFactory.test.ts
- administration/src/cards/createCards.ts
- administration/src/cards/deleteCards.ts
- administration/src/project-configs/getProjectConfig.ts
- administration/src/util/__tests__/getCustomDeepLinkFromQrCode.test.ts
- administration/src/util/helper.ts
Refactor useCardGenerator and useCardGeneratorSelfService hooks and other utilities.
- Move card initialization from query params to useCardGenerator
- Extract code from hooks to new files useSendConfirmationMail and cardGenerationError and some old files
- Reuse code between useCardGenerator and useCardGeneratorSelfService
- Refactor createCards, CsvFactory, deleteCards, PdfFactory
- Pdf download name for self service is now `KoblenzPass.pdf` instead of `KoblenzPass`
- Opening a csv in card import, navigating back (accepting the popup) leads to an error (however, this is the same on main and I was not able to reproduce this on staging).
Test everything related to card generation (normal + self service) and csv and pdf generation.
Fixes: #1799
> 1799: Refactor useCardGenerator and useCardGeneratorSelfService

- administration/src/KeepAliveToken.tsx
- administration/src/WhoAmIProvider.tsx
- administration/src/bp-modules/NavigationBar.tsx
- administration/src/bp-modules/UserMenu.tsx
- administration/src/bp-modules/applications/ApplicationsController.tsx
- administration/src/bp-modules/cards/AddCardsController.tsx
- administration/src/bp-modules/cards/CreateCardsController.tsx
- administration/src/bp-modules/cards/ImportCardsController.tsx
- administration/src/bp-modules/home/HomeController.tsx
- administration/src/bp-modules/project-settings/ProjectSettingsController.tsx
- administration/src/bp-modules/regions/RegionController.tsx
- administration/src/bp-modules/regions/data-privacy-policy/DataPrivacyController.tsx
- administration/src/bp-modules/statistics/StatisticsController.tsx
- administration/src/bp-modules/statistics/StatisticsOverview.tsx
- administration/src/bp-modules/stores/StoresController.tsx
- administration/src/bp-modules/stores/StoresImportController.tsx
- administration/src/bp-modules/user-settings/ChangePasswordForm.tsx
- administration/src/bp-modules/user-settings/UserSettingsController.tsx
- administration/src/bp-modules/users/ManageUsersController.tsx
- administration/src/bp-modules/users/RoleSelector.tsx
- administration/src/util/helper.ts
Avoid non-null assertions for who am i by creating a hook.
- Create a hook to expose the context non-nullable
- Using the hook is only possible if `me` is actually not null, so when a user is logged in
Ensure that everything still works.
Fixes: #1953
> 1953: Avoid non-null assertions for WhoAmI

- frontend/.idea/frontend.iml
All flutter dart files of plugins are in the `.symlink` folder. That makes searching of code for dart super difficult.
- exclude symlink (plugins) 
- exclude build (not needed)
- none
N/A
> Exclude ios folders

- frontend/lib/store_widgets/detail/detail_content.dart
Currently we are facing an (handled) error if an address of a store was opened on ios
- add launch mode external for ios
- Apple maps is opened directly without safari. I guess that shouldn't be a problem though, since "Maps" can't be deleted from an ios device
- Open a store in bayrische ehrenamtskarte f.e. search for "Brückstraße" then open on the detail view the address. There shouldn't be error in the console anymore
Fixes: #1285
> 1285: Fix launching apple maps

- backend/build.gradle.kts
Apparently `detekt` is run on all Gradle builds within the "check" phase and there is [no easy API](https://github.com/detekt/detekt/discussions/4196) to just skip this, so ignore the errors (for now).
-
-
Fixes: #
> Do not fail build when running detekt

- .circleci/config.yml
- .circleci/src/commands/install_app_toolbelt.yml
- .circleci/src/commands/install_node_modules.yml
- .circleci/src/jobs/build_administration.yml
- .circleci/src/jobs/bump_version.yml
- .circleci/src/jobs/check_administration.yml
- .circleci/src/jobs/notify_release.yml
- .circleci/src/jobs/promote_github_release.yml
- administration/package.json
- docs/cicd.md
- docs/development-setup.md
- frontend/android/buildSrc/src/main/kotlin/BuildConfig.kt
- frontend/android/fastlane/Fastfile
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/bayern.xcscheme
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/koblenz.xcscheme
- frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/nuernberg.xcscheme
- frontend/ios/fastlane/Fastfile
- frontend/pubs/df_build_config/lib/builder.dart
- frontend/pubspec.lock
- package-lock.json
- package.json
Use local app-toolbelt installation instead of installing it globally.
I frequently run into troubles because a path is not set, app-toolbelt is not detected or the wrong node version is used. By adding app-toolbelt locally, we can get rid of one step in t
- Add app-toolbelt to package.json
- Use app-toolbelt from local node_modules instead of global installation
1. An `npm install` is now needed in the CI to use the app-toolbelt
2. In order to install a newer app-toolbelt version (e.g. switch to `v0.3`), you need to either
- `npm install app-toolbelt --force --no-save`
- delete node_modules and run `npm install` again OR
- remove `app-toolbelt` from package.json, run `npm install`, readd it with the correct version and run `npm install` again
However, this is only a local problem as in …
> Use local app-toolbelt installation

- administration/package.json
- administration/src/bp-modules/StickyBottomBar.tsx
- administration/src/bp-modules/cards/AddCardForm.tsx
- administration/src/bp-modules/components/CustomDatePicker.tsx
- administration/src/bp-modules/statistics/StatisticsController.tsx
- administration/src/bp-modules/statistics/components/StatisticsFilterBar.test.tsx
- administration/src/bp-modules/statistics/components/StatisticsFilterBar.tsx
- administration/src/bp-modules/statistics/constants/index.ts
- administration/src/cards/extensions/BirthdayExtension.tsx
- administration/src/cards/extensions/StartDayExtension.tsx
- administration/src/mui-modules/application/SteppedSubForms.tsx
- administration/src/mui-modules/application/forms/JuleicaEntitlementForm.tsx
- administration/src/mui-modules/application/forms/WorkAtOrganizationForm.tsx
- administration/src/mui-modules/application/primitive-inputs/DateForm.tsx
- package-lock.json
Replaces `<TextField>` components in `DateForm` with `<CustomDatePicker>`.
- Updates the package `@mui/x-date-pickers` to 7.27.3.
- Replaces the `<TextField>` component in `DateForm` with `<CustomDatePicker>` components. 
- Uses `enableAccessibleFieldDOMStructure` for `<CustomDatePicker>`, which will be the [future default](enableAccessibleFieldDOMStructure) for MUI components.
- Uses the proper `format` for `<CustomDatePicker>`, fixing the text input. The format will also be displayed and having the month fields in lower case looks slightly misplaced, but I think this is tolerable. Could be fixed with some more CSS.
- Remove some box shadows that looked misplaced.
- Make all event handlers optional in `<CustomDatePicker>`.
None.
- Start backend and frontend
- Visit …
> 1766: Unify date picker components 

- administration/src/mui-modules/application/forms/StepCardTypeForm.tsx
At Bayerns form when you select the golden card and uncheck the checkbox on digital and physical options it will let you continue until the final stage where it will say Daten konnten nicht geparsed werden.  without indication where is the missing field/box.
- Just putting the partialValidationResult checking above the return for the golden card
`if (partialValidationResult.value.cardType !== BavariaCardType.Blue)`
none.
- Go to http://localhost:3000/beantragen
- Fill the form normally but select the golden card and remove the checkbox on digital and physical options.
- Test also the blue card's digital and physical options.
Fixes: #2002
> 2002: Golden Card validation

- administration/src/cards/Card.test.ts
- administration/src/cards/extensions/AddressFieldExtensions.ts
- administration/src/util/helper.ts
Since only latin and common charset is working for pdf creation, we should add a check to character fields that will be used in the pdf creation.
Even for address field the pdf creation may not break but result in invalid characters as you can see here.
This is how the pdf will look without the check (currently)
- add a check to the `isValid()` function of the address fields
- add a test for csv lines that contain arabic characters
- none
1. Switch to nuernberg
2. Add f.e. arabic characters or emojis to the card import csv files for character fields like name and address fields
3. Import the csv file
4. Check the table preview that it marks the invalid fields and cards can not be created
Fixes: #1776
> 1776: Character restriction address fields

- .circleci/config.yml
- .circleci/src/jobs/build_ios.yml
- .circleci/src/jobs/deliver_ios.yml
- .circleci/src/jobs/promote_ios.yml
Due to not being able to push new ios releases starting 24th of april with xcode 15 builds (ios 17 sdk), we have to update to XCode 16.x.x
- i tried to update to latest circle ci version (16.2.0) but got some errors with signing: [here](https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/7963/workflows/0a737d86-63d1-4af2-be49-be10284bb3a7/jobs/53904)
- so i updated to xcode 16.1.0 since its quite urgent and Version 16.1.0 also used ios sdk 18
- likely none
Check build ios job in the `commit_main` workflow
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard?branch=2035-update-xcode-16.1.0
Fixes: #2035
> 2035: Update xcode to 16.1.0

- .idea/runConfigurations/Run__env_local_buildConfig_bayern_.xml
- .idea/runConfigurations/Run__env_local_buildConfig_koblenz_.xml
- .idea/runConfigurations/Run__env_local_buildConfig_nuernberg_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_bayern_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_koblenz_.xml
- .idea/runConfigurations/Run__env_production_buildConfig_nuernberg_.xml
- frontend/lib/main.dart
There is an issue that not all locales will be loaded initially with the current `slang` plugin version
https://github.com/slang-i18n/slang/issues/294
I added the workaround that they provided there
- add load function to to add all locales on app start, since they were not properly initialized
- add comment to remove this workaround when new slang version was released (#2061)
- adjust runConfigs to use the flavor lowercase in the particular `buildFlavor`part. That seem to fix the issues tory mentioned
- likely none
See the issue instructions
Fixes: #2052
> 2052: Workaround translation overrides ios

- frontend/ios/fastlane/Fastfile
This adds the needed flavors for #1703 to the fastlane ios build
- add flavor to xcargs to be provided in the build
- likely none
I uploaded this ipa to browserstack
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8008/workflows/782de0d0-bd27-4c66-ab84-bb55085b9026/jobs/54296/artifacts
Check the ipa in browserstack (test-flavor-nuernberg.ipa)
https://app-live.browserstack.com/#os=iOS&os_version=18.0&zoom_to_fit=true&full_screen=true&speed=1
In comparison you can test the broken one `nuernberg.ipa` from main branch also in browserstack
Fixes: #2089
> 2089: Add flavor ios build fastlane

- .circleci/config.yml
- .circleci/src/jobs/build_administration.yml
- .circleci/src/jobs/build_android.yml
- .circleci/src/jobs/build_backend.yml
- .circleci/src/jobs/check_administration.yml
- .circleci/src/jobs/check_backend.yml
- .circleci/src/jobs/deliver_server.yml
- .circleci/src/jobs/pack_administration.yml
- .circleci/src/jobs/pack_backend.yml
- .circleci/src/jobs/pack_martin.yml
- .circleci/src/jobs/pack_meta.yml
- .circleci/src/jobs/promote_github_release.yml
- .circleci/src/jobs/promote_server.yml
I just realized that we nearly nowhere set the resource class to use in the CI. Therefore the default `medium` is used which costs us a ton of credits.
- Use `resource_class: small` wherever possible (all jobs except macos and `build_android` (large) and `build_administration` (medium))
- For macOS the default already is m1 medium which is the cheapest
Jobs might take slightly longer.
See that the CI succeeds: https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8028/workflows/1669cbbe-3260-40b7-9e35-02ad1162fe07
Fixes: N/A
> Use resource class small to save credits

- frontend/graphql_queries/stores/accepting_stores_search.graphql
- frontend/graphql_queries/stores/physical_store_by_id.graphql
- frontend/graphql_queries/stores/physical_store_summary_by_id.graphql
- frontend/lib/favorites/favorite_store.dart
- frontend/lib/favorites/favorites_loader.dart
- frontend/lib/home/home_page.dart
- frontend/lib/map/floating_action_map_bar.dart
- frontend/lib/map/preview/accepting_store_preview.dart
- frontend/lib/map/preview/accepting_store_preview_card.dart
- frontend/lib/map/preview/models.dart
- frontend/lib/search/results_loader.dart
- frontend/lib/store_widgets/accepting_store_summary.dart
- frontend/lib/store_widgets/detail/detail_content.dart
- frontend/lib/store_widgets/detail/detail_page.dart
- frontend/test/favorites/favorites_page_test.dart
We mix accepting store ids and physical store ids in the frontend.
On staging, these ids sometimes differ and thus we sometimes query physical stores using an invalid id.
Interestingly, on production, the ids always match, so we did not run into the bug yet.
* Adjust naming of related queries and fields to explicitly specify accepting store id vs physical store id.
* Use physical store id instead of accepting store id when appropriate
None
* In the Bayern EAK staging app:
* Search for "Anna Apotheke"
* Clicking on it should successfully open the detail page of the Anna Apotheke
> Fix querying for wrong physical store id

- .github/dependabot.yaml
Enables automatic dependency updates.
As suggested in the issue description, I (tried to) allow only minor&patch version updates.
Also I limited the bot to only 2 open pull requests for each package-ecosystem.
Feel free to discuss the config :)
Fixes: #1907
> 1907: Enable dependabot updates

- administration/src/cards/extensions/NuernbergPassIdExtension.tsx
In the card creation form, it was possible to enter Nürnberg-Pass-ID = 9999999999, but an error occurred when generating the card.
Set the max length of the of nürnberg pass id to 9
no
1. Login to Nürnberg administration as region admin
2. Go to "Karten erstellen" --> "Einzelne Karten erstellen"
3. Check that it is not possible to enter Nürnberg-Pass-ID = 9999999999 (10 chars). Only 9 characters are allowed.
Additionally can be checked that a card with Nürnberg-Pass-ID = 999999999 (9 chars) can be generated without errors.
Fixes: #1999
> 1999: Limit the Nürnberg Pass-Id to 9 characters

- .github/dependabot.yaml
This adds a not testable label for dependabot prs. I think for most of the minor package update this should be fine.
If you think we should set it for every pr manually, feel free to reject.
- add "not-testable" label
> Add not testable dependabot

- docker-compose.yml
There was a race condition seemingly introduced in https://github.com/digitalfabrik/entitlementcard/pull/2116 that results in (sometimes) martin not being able to launch correctly; it seems to fail to connect to the DB.
Therefore, we should make docker compose wait for the DB to spin up completely.
I also adjusted the version of the postgis container to match the postgres version we use in Salt.
> Local setup: Let Martin wait for db, sync DB version with salt

- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/database/repos/RegionsRepository.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/schema/RegionsQueryService.kt
Currently a 500 error (check console) occurs if the user types a postal code in the application form that has no valid `regionIdentifier`(ars) in our `regions` table. You can find example postal codes in the issue comment.
Note: We use a csv file that consists all postalCodes and the corresponding regionIdentifiers to find the `ars` for a particular postal code, since a region can have multiple postal codes but has one single (4 digit) ars
- adjust `findRegionByRegionIdentifier` to return `.singleOrNull)` before it was unsafely tried to get the region via id that couldn't be found in some cases and leading to internal error
- concatenate filtering regions by postalCode and finding the region by ars in the database
- likely none
- type in a postal code that has no corresponding ars in our …
> 2003: Fix uncaught exception regions by postal code

- package-lock.json
- package.json
Currently the latest flag is not set when promoting a github release
- use new app-toolbelt version that correctly sets the latest flag
- none
Fixes: #2153 
related: https://github.com/digitalfabrik/app-toolbelt/pull/32
> 2153: Fix latest

- administration/package.json
- package-lock.json
Apparently the update to `react-router-dom 6.30.0` breaks the redirects for login and logout.
This is described here #2148
Note this is only a workaround to fix the issue. I also created an issue for updating react router to v7 (#2161)
- downgrade react router dom
- none
1. Remove `node_modules` from administration and root folder(dev only)
2. run `npm i` and start administration (dev only)
3. Login should redirect to `/` and logout to the login form , check that this does not happen #2148
I will keep #2148 open because its just a workaround.
> Downgrade react-router-dom

- administration/src/util/__tests__/getCustomDeepLinkFromQrCode.test.ts
- administration/src/util/__tests__/getDeepLinkFromQrCode.test.ts
- administration/src/util/getCustomDeepLinkFromQrCode.ts
- administration/src/util/getDeepLinkFromQrCode.ts
- docs/deep-linking.md
- frontend/lib/activation/deeplink_activation.dart
- frontend/lib/app.dart
- frontend/lib/util/string_utils.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
The old `go_router` version didn't resolve url fragments properly without trailing slash, thats why we added some trailings slashes to the deeplinks.
This was not really a good practise since base64 strings could also include `/` 
This is quite error prone.
- update got router to recent
- remove trailing slashes from deeplinks
- add legacy support for old deep links
- adjust tests
- Likely none
- Create cards for koblenz (/erstellen) and activate the card
- Create a card for bavaria and copy the custom scheme deeplink in the browser
- Use the command in `deeplinks.md`(devs only)
- `npx uri-scheme open https://staging.nuernberg.sozialpass.app/activation/code#<activationCode> --android`
Test legacy support:
- add to the deeplink a trailing slash using the command line (dev only)
- `npx …
> 1679: Update go router

- frontend/lib/about/about_page.dart
- frontend/lib/identification/card_detail_view/card_carousel.dart
- frontend/lib/identification/identification_page.dart
- frontend/lib/identification/no_card_page.dart
- frontend/lib/map/map_page.dart
- frontend/lib/themes.dart
- frontend/lib/widgets/app_bars.dart
The system ui overlay was not properly configured:
* on some screens in dark mode (e.g. Ausweisen, About), the system status bar was dark on a dark background (=> illegible)
* on some screens (e.g. Search Page, Herausgeber, etc.), the system status bar was dark, but the title on our app bar was white (=> visually ugly, but all was legible)
Usually, the system ui overlay style is handled through the use of an AppBar.
I added a minimal appbar for status bar protection (using a Gradient) for the Ausweisen and About pages (the protections are especially relevant for landscape mode, where the content exceeds the viewport and can be scrolled).
For the maps page, we likely don't want to further protect the status bar (Google Maps does not do that either; it would look a bit weird), so we can use …
> 2094: Improve system overlay and top unsafe area handling

- administration/src/project-configs/bayern/dataPrivacyBase.tsx
- frontend/build-configs/bayern/disclaimerText.ts
- frontend/build-configs/bayern/publisherText.ts
In the Ehrenamtskarte app the "Referat Öffentlichkeitsarbeit" is mentioned as the responsible agent for the contents of the app. They asked us to change this to "Referat III 3".
- adjust department name in the app and in the administration
no
Check the department name in the Ehrenamtskarte app:
- "Über" -> "Mehr Informationen"
- "Über" -> "Haftung, Haftungsausschluss und Impressum"
Check the name in the Datenschutzerklärung (last step of the application submission form)
Fixes: #2169
> 2169: Change name of responsible department for the EAK

- backend/build.gradle.kts
Fix KOBLENZ_PEPPER in gradle config
Fix KOBLENZ_PEPPER in gradle config
These variables wont be used on production, right? (not sure how do we run backend there)
Card creation for Koblenz should work locally 
Fixes: #2190
> 2190: Fix KOBLENZ_PEPPER in gradle config

- backend/src/main/kotlin/app/ehrenamtskarte/backend/cards/webservice/schema/CardMutationService.kt
Card activation is currently broken
Exception in the backend:
```
[JettyServerThreadPool-287] WARN io.javalin.Javalin - Uncaught exception
java.lang.IllegalArgumentException: maxAttempts must be set to perform at least 1 attempt.
at org.jetbrains.exposed.sql.Transaction.setMaxAttempts(Transaction.kt:77)
at app.ehrenamtskarte.backend.cards.webservice.schema.CardMutationService.activateCard$lambda$4(CardMutationService.kt:312)
```
Change the transaction's max attempts property to 1 so that the transaction is executed once instead of never
no
1. create card (for any project)
2. activate/add card in the app
n/a
> Fix card activation

- .github/dependabot.yaml
Groups dependabot updates and reduces frequency to reduce the number of PRs.
n/a
Could someone with sufficient permissions check in the repository settings whether we have to enable dependabot security updates (and if so enable them)? I have no access to the repo settings...
Here's a guide:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
> Group dependabot updates and reduce frequency

- .github/dependabot.yaml
We had some issues with minor group updates on npm, so i reverted to single for minor and group for patch versions
- group updates for patch versions 
- single updates for minor versions
- weekly single updates for other ecosystems with few dependencies
- add workaround for multiple update schedules on one ecosystem
- should be none
There is a validation tool for the syntax
https://www.npmjs.com/package/@bugron/validate-dependabot-yaml
The rest can only be checked if its merged in main afaics
Fixes: #
> dependabot: Group updates patch single minor

- administration/src/cards/extensions/StartDayExtension.tsx
The plainDate of the startDay was not constructed safely
- use SafeFromLocalDate to safely construct plain date 
- add null for initial value as fallback to avoid controlled/uncontrolled error in the console
- none
1. Login nuernberg project
2. Go to Karte erstellen
3. Click in startDay form and try to change the value
4. No error should be shown
Fixes: #2239
> 2239: Runtime error start date

- scripts/pack_deb.sh
Since we had some issue that after a package update, the backend service was not restarted successful, i added a service restart in the debian package post install step.
- backend service restart in the backend debian package post install step
- should be none, if migration runs first
Only testable when new package will be installed in the server
> Post install restart backend after migration

- administration/config/getPaths.ts
Use '/' as the root path for referencing any (JS) assets.
Fixes a bug introduced in #2219 .
Build the production app and verify that the index.html references the JS asset with "/" instead of "http://localhost:3000/".
Fixes: #2267
> 2267: Use '/' as public URL instead of localhost

- .circleci/config.yml
- .circleci/src/jobs/build_backend.yml
- backend/build.gradle.kts
Currently `./gradlew assemble` will fail if we don't provide sentry auth token as environment variable.
For local dev, we don't need sentry at all, so we can exclude it also for the build
- only use sentry config for production builds
- use production environment variable in build gradle
- add prod env variable to pipeline to build with sentry  
- none
Check in the issue description
`build_backend` should still work
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8587/workflows/0e8fb6e7-836a-4868-8aaa-7866949d2948
Fixes: #2260
> 2260: Use sentry only for gradle production builds

- administration/package.json
- administration/src/bp-modules/applications/ApplicationsOverview.tsx
- administration/src/bp-modules/cards/AddCardsForm.tsx
- package-lock.json
Replace package `react-flip-move` with [motion](https://github.com/motiondivision/motion) (formerly known as `framer-motion`) for animating lists.
None
- Visit http://localhost:3000/cards/add to add and remove card items
- Visit http://localhost:3000/applications and delete applications
Fixes: #2176
> 2176 Replace `react-flip-move` with `motion`

- .circleci/config.yml
- .circleci/src/jobs/build_android.yml
- .circleci/src/jobs/build_ios.yml
- frontend/android/gradle.properties
New kotlin version requires ninja.
- add ninja that are required for fastlane android builds
- added some gradle properties to speedup gradle build a bit
- adjusted macos ressource class to fix deprecation warning
-
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8843/workflows/c59259eb-089b-4761-9cd6-1a10978b271f
Fixes: #
> Fix android builds ninja cmake

- administration/src/bp-modules/statistics/components/StatisticsBarChart.tsx
I tried to add left and bottom axis lines to cards statistics according to the design
https://www.figma.com/design/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?node-id=1003-6294&t=bmDIoa0F2pLbxZgv-0
Add CustomAxisLines
no?
see https://github.com/digitalfabrik/entitlementcard/pull/2331
Part of https://github.com/digitalfabrik/entitlementcard/pull/2331
> 1760: Add left and bottom axis lines to cards statistics

- frontend/lib/activation/deeplink_activation.dart
When the user opens an invalid deeplink, the error message container should be center even if the text length does not need the entire screen width
- wrap error container with `Center` widget
- none
1. `npx uri-scheme open ehrenamtbayern://bayern.ehrenamtskarte.app/activation/code# --ios`
2. Test same for `--android`
Fixes: #2336
> 2336: Misaligned card activation error

- .idea/modules.xml
- administration/src/bp-modules/applications/ApplicationCard.tsx
- administration/src/graphql/applications/rejectApplicationStatus.graphql
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationJsonExtensions.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/freinet/webservice/FreinetApplicationMutationService.kt
- backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
- specs/backend-api.graphql
Send an email to applicant for an Ehrenamtskarte Bayern if their application is rejected
- add sending email to rejectApplicationStatus mutation
- bugfix: if the application has already been approved - the rejectApplicationStatus mutation returned a successful response and a rejectionMessage was added to the application. I added an exception for the case when the request has already been processed.
- add ApplicationJsonExtensions util and clean up FreinetApplicationMutationService a bit
no?
- create an application
- login as region admin, reject the created application
- check that the corresponding email has been sent to the applicant
Fixes: #1983
> 1983: Send application rejected mail

- administration/src/bp-modules/applications/ApplicationsOverview.tsx
Print dialog currently adds lots of whitespace before and after the application, depending on the scroll position of the list
- remove gap for printing view
- none
1. Go to "Eingehende Anträge"
2. Scroll down the application list
3. Click export pdf
4. Application shouldn't have whitespace before and after the application details
Fixes: #2375
> 2375: Fix print dialog

- .circleci/config.yml
- .circleci/src/workflows/promotion_all.yml
- .circleci/src/workflows/promotion_frontend.yml
At a few places the `mattermost` context was used while in most place the environment variable was used directly.
This PR changes it to consistently use the env variable directly.
- Use mattermost environment variable over context
N/A
N/A
Fixes: N/A
> Use mattermost environment variable over context

- administration/src/mui-modules/base/AlertBox.tsx
- administration/src/mui-modules/util/getQueryResult.tsx
Currently we are facing errors if retry was executed for an request using `AlertBox`
- execute `onAction` with arrow function
- pass `severity: 'error'`
- none
- open this route to get an erroneous request : http://localhost:3000/antrag-einsehen/hjh
- check the network tab for requests or backend service (devs)
Fixes: #2397
> 2397: Fix retry

- administration/src/errors/DefaultErrorMap.ts
- administration/src/errors/getMessageFromApolloError.ts
- administration/src/mui-modules/base/AlertBox.tsx
- administration/src/mui-modules/util/getQueryResult.tsx
Currently we show a retry button even a retry could not solve the issue (for all graphql errors f.e.)
- add retryable option in `GraphQLErrorMessage`
- only show retry button if it's needed
- remove AlertBox vertical style for mobile
- none
Fixes: #
> 2396: Invalid application link alignment

- administration/src/bp-modules/applications/components/ApplicationStatusNote.tsx
Icon of Application status note is rendered as a string instead html icon component
- wrap icon with fragment
- Open "Eingehende Anträge", process (accept or reject) application. check status note icon will be rendered correctly
Fixes: #2457
> 2457: Fix application note icon
