README.md
frontend/README.md

#1 Create list of resources about EAK and OZG

---

frontend/ios/Flutter/Debug.xcconfig
frontend/ios/Flutter/Release.xcconfig
frontend/ios/Runner.xcodeproj/project.pbxproj
frontend/ios/Runner.xcworkspace/contents.xcworkspacedata
frontend/ios/Runner/Info.plist
frontend/pubspec.lock
frontend/pubspec.yaml

#24 flutter add permission management

---

frontend/ios/Flutter/AppFrameworkInfo.plist

#80 revert flutter subproject bundle id to original id

---

backend/src/main/kotlin/xyz/elitese/ehrenamtskarte/webservice/GraphQLHandler.kt
backend/src/main/kotlin/xyz/elitese/ehrenamtskarte/webservice/WebService.kt

#87: Fix logger exception

---

frontend/lib/home/home_page.dart

#92 keep tabs alive

---

frontend/lib/map/map/map.dart

#97: Animate Store Click on Map

---

frontend/lib/map/map/map.dart

99: Enlarge selected symbol

---

frontend/lib/app.dart
frontend/lib/graphql/configured_graphql_provider.dart
frontend/lib/home/home_page.dart

* removed unused title parameter
* extracted GraphQL configuration from app.dart (low coherence)

Frontend refactoring

---

frontend/lib/map/map/map.dart
frontend/lib/map/map/map_with_futures.dart

#123 do not zoom in if location services are disabled

---

frontend/lib/search/results_loader.dart
frontend/lib/search/search_page.dart

This closes #135 and adds additional improvements to the search, including like error/progress indicators.

#135 search improvements

---

frontend/lib/identification/id_card.dart
frontend/lib/identification/identification_page.dart

#147 make identification page scrollable

---

frontend/lib/search/seach_result_item.dart

#158 make search results null aware

---

frontend/lib/map/detail/detail_layout.dart
frontend/lib/map/detail/detail_view.dart

#113 show category name on detail screen

---

frontend/lib/search/search_page.dart

#184 add clear search button

---

frontend/lib/more/more_page.dart

#209 remove singlechildscrollview which collides with the scroll functionality of gridview

---

administration/__generated__/globalTypes.ts
administration/package-lock.json
administration/package.json
administration/src/components/generation/generateCards.tsx
administration/src/graphql/customScalarTypes.d.ts
administration/src/polyfills.tsx
administration/src/util/generateHashFromCardDetails.ts
administration/tsconfig.json

217: Properly hash card details

---

frontend/android/app/src/main/kotlin/app/ehrenamtskarte/android/MainActivity.kt
frontend/lib/map/map/attribution_dialog.dart
frontend/lib/map/map/attribution_dialog_item.dart
frontend/lib/map/map/map.dart
frontend/lib/map/map/map_controller.dart
frontend/lib/map/map_page.dart

250 Give proper attribution

---

frontend/ios/Runner/Info.plist
frontend/lib/home/home_page.dart
frontend/lib/location/determine_position.dart
frontend/lib/map/map/map.dart
frontend/lib/map/map_page.dart

249 ios improvements

---

frontend/android/app/build.gradle
frontend/android/build.gradle
frontend/android/gradle.properties
frontend/android/gradle/wrapper/gradle-wrapper.properties
frontend/lib/graphql/configured_graphql_provider.dart
frontend/lib/graphql/graphql_api.graphql.dart
frontend/lib/graphql/graphql_api.graphql.g.dart
frontend/lib/identification/identification_qr_content_parser.dart
frontend/lib/map/detail/detail_view.dart
frontend/lib/map/preview/loading_accepting_store_summary.dart
frontend/lib/qr_code_scanner/qr_code_scanner.dart
frontend/lib/qr_code_scanner/qr_code_scanner_controls.dart
frontend/lib/search/results_loader.dart
frontend/lib/verification/view/verification_result.dart
frontend/pubspec.lock
frontend/pubspec.yaml

#248 update some dart packages

---

docker/reverse_proxy/nginx-staging.conf
docs/staging-setup.md

Fix staging deployment

---

frontend/lib/identification/animated_progressbar.dart
frontend/lib/identification/rectangular_progress_indicator_painter.dart
frontend/lib/identification/verification_qr_code_view.dart

Whoopsiedaisy
Let me know whether you like, and what to improve :D
https://user-images.githubusercontent.com/7025199/110248854-5b9e4e00-7f73-11eb-91ec-a0c38400881a.mp4

Polish QR-Code animation

---

frontend/lib/identification/card_detail_view.dart
frontend/lib/verification/view/result_card/positive_verification_result.dart
frontend/lib/verification/view/verification_result.dart

#289 fix crash with invalid region IDs

---

README.md
administration/Dockerfile
docker-compose.staging.yml
docker/reverse_proxy/nginx-staging.conf
docs/production-setup.md
docs/staging-setup.md

320 staging druckerei

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/JwtService.kt
docker-compose.staging.yml

315 jwt setting

---

frontend/lib/application/application_form.dart
frontend/lib/application/card_type_step.dart
frontend/lib/application/entitlement/certificate.dart
frontend/lib/application/entitlement/entitlement_juleica.dart
frontend/lib/application/entitlement/entitlement_service_blue.dart
frontend/lib/application/entitlement/entitlement_work.dart
frontend/lib/application/entitlement/organization_divider.dart
frontend/lib/application/entitlement/work_at_organization.dart
frontend/lib/application/entitlement_step.dart
frontend/lib/application/entitlement_type_blue.dart
frontend/lib/application/entitlement_type_gold.dart
frontend/lib/application/entitlement_type_step.dart
frontend/lib/application/personal_data_step.dart
frontend/lib/application/region_step.dart
frontend/lib/application/summary_step.dart
frontend/lib/graphql/graphql_api.graphql.dart
frontend/lib/graphql/graphql_api.graphql.g.dart
frontend/lib/identification/card_detail_view/card_detail_view.dart
frontend/lib/identification/card_detail_view/more_actions_dialog.dart
frontend/lib/identification/identification_page.dart
frontend/lib/identification/no_card_view.dart

See my review comments in #305 for explanations.

#288 improve application code

---

.idea/runConfigurations/Run_Backend.xml
administration/src/App.tsx
backend/.gitignore
backend/gradle.properties
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/EakApplicationRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/registerApplicationJavalinHandler.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/JwtService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLContext.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLHandler.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/WebService.kt
docker-compose.staging.yml

326 store attachments

---

frontend/lib/verification/dialogs/positive_verification_result_dialog.dart
frontend/lib/verification/query_server_verification.dart

- fix backend verification result being cached by graphql
- fix null exception when region was still loading in positive_verification_result

Frontend verification improvements

---

frontend/ios/Runner/Info.plist

337 add NSPhotoLibraryUsageDescription for image picker in application form

---

administration/src/components/generation/PdfFactory.ts

#267: Use correct gender term

---

frontend/android/app/build.gradle
frontend/android/app/proguard-rules.pro

#340: Fix release build by some proguard magic

---

frontend/lib/map/map/map.dart
frontend/lib/map/map/map_with_futures.dart

#345: Fix jumping map

---

administration/.env.development
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/EakApplicationRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
frontend/.fvm/fvm_config.json
frontend/.gitignore
frontend/README.md
frontend/lib/about/dev_settings_view.dart
frontend/lib/about/texts.dart
frontend/lib/intro_slides/intro_screen.dart
frontend/pubspec.lock
frontend/pubspec.yaml

closes #358 
closes #357 
closes #360

358, 357, 360 Application improvements and fixed stmas address

---

frontend/lib/about/about_page.dart

i mean it is open source, why not add a link to it? :)

link to our github project in the about_page

---

frontend/lib/map/map/map.dart

This needs to be tested on iOS. Also check whether the store in Diedorf is selectable.

375: Increase map icon touch target

---

frontend/lib/intro_slides/location_request_button.dart
frontend/lib/location/determine_position.dart
frontend/lib/map/location_button.dart
frontend/lib/map/map/map.dart
frontend/lib/map/map/map_controller.dart
frontend/lib/map/map/map_with_futures.dart
frontend/lib/search/location_button.dart

fixes #389 
fixes #393 
TODO: Write descripction about PR

IGAPP-389: Refactor location permission handling

---

map-tiles/styles/map.html

Fix maplibre on web preview

---

frontend/lib/about/about_page.dart
frontend/lib/about/content_tile.dart
frontend/lib/about/dev_settings_view.dart
frontend/lib/about/license_page.dart
frontend/lib/application/application_form.dart
frontend/lib/identification/identification_qr_scanner_page.dart
frontend/lib/identification/no_card_view.dart
frontend/lib/qr_code_scanner/qr_code_scanner_page.dart
frontend/lib/store_widgets/detail/detail_page.dart
frontend/lib/verification/dialogs/negative_verification_result_dialog.dart
frontend/lib/verification/verification_workflow.dart
frontend/lib/widgets/top_loading_spinner.dart

We used a predefined License which does not value the design of our app. It also includes a scaffolding which should not be done.
This is a base which could be polished, but at the same time it is also acceptable for production.

Custom license page

---

frontend/lib/about/dev_settings_view.dart
frontend/lib/configuration/settings_model.dart
frontend/lib/home/home_page.dart
frontend/lib/intro_slides/location_request_button.dart
frontend/lib/location/determine_position.dart
frontend/lib/map/location_button.dart
frontend/lib/search/location_button.dart
frontend/lib/store_widgets/detail/detail_app_bar.dart

This PR contains fixes and improvement to the location permission detection. (especially for iOS)

Fix permissions on iOS

---

frontend/android/app/src/main/AndroidManifest.xml
frontend/lib/store_widgets/detail/detail_app_bar.dart

Sadly I dont know how to fix this else. I don't even know where to start...

Fix Map Rotation

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/Map.kt

Remove subsequent spaces

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/FilterDuplicates.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/MapFromLbe.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/SanitizeAddress.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/types/AcceptingStore.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/types/LbeAcceptingStore.kt

Fix import

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/LbeDataImporter.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/steps/PostSanitizeFilter.kt

Dont filter stores outside of state

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLHandler.kt

Fix crash in backend

---

frontend/lib/map/map/map.dart

498 Adjust min max zoom

---

.idea/runConfigurations/Test_Backend.xml
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/PasswordValidator.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/auth/PasswordValidatorTest.kt

482: Check and validate password policies

---

backend/build.gradle.kts
backend/src/main/kotlin/app/ehrenamtskarte/backend/map/webservice/MapStyleHandler.kt

Fix loading of style.json

---

frontend/build-configs/bayern/index.ts

We aim to support it already with the whitelabel branch.

Enable verification for bayern

---

administration/src/components/Navigation.tsx
administration/src/components/RegionSelector.tsx
administration/src/components/auth/ForgotPasswordController.tsx
administration/src/components/auth/ResetPasswordController.tsx
administration/src/components/users/CreateUserDialog.tsx
administration/src/components/users/ManageUsersController.tsx
administration/src/components/users/RoleHelpButton.tsx
administration/src/components/users/UsersTable.tsx
administration/src/graphql/users/createAdministrator.graphql
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Schema.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/repos/AdministratorsRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/service/Authorizer.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/authGraphQLParams.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ManageUsersMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
specs/backend-api.graphql

665: Create admin from administration

---

administration/src/util/generateHashFromCardDetails.ts
frontend/lib/about/dev_settings_view.dart
frontend/lib/verification/verification_hasher.dart
frontend/lib/verification/verification_qr_scanner_page.dart

* Self verify button
* option to add card in About tab
* Fixed endless loading spinner
* Fixed broken card verification

Add dev tool to add a card

---

administration/src/components/getMessageFromApolloError.tsx
administration/src/components/users/CreateUserDialog.tsx
administration/src/components/users/EditUserDialog.tsx
administration/src/components/users/RoleSelector.tsx
administration/src/components/users/UsersTable.tsx
administration/src/graphql/users/editAdministrator.graphql
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/service/Authorizer.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ManageUsersMutationService.kt
specs/backend-api.graphql

Edit Users

---

.idea/runConfigurations/Create_project_admin__env_local_buildConfig_bayern_.xml
.idea/runConfigurations/Create_region_admin__env_local_buildConfig_bayern_.xml
.idea/runConfigurations/Create_region_manager__env_local_buildConfig_bayern_.xml

Added a config for creating region admins.
Changed the project to bayern.entitlementcard.app

Fix run configs for creating users

---

.idea/kotlinc.xml
backend/build.gradle.kts
backend/gradle.properties
backend/src/main/kotlin/app/ehrenamtskarte/backend/EntryPoint.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/applicationGraphQLParams.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ManageUsersMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/constants.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/config/BackendConfiguration.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/SendMail.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardQueryService.kt
backend/src/main/resources/config/.gitignore
backend/src/main/resources/config/config.yml

Setup SMTP

---

frontend/build-configs/bayern/index.ts
frontend/build-configs/nuernberg/index.ts
frontend/build-configs/types.ts
frontend/lib/themes.dart

523: Configure theme

---

frontend/lib/verification/dialogs/internet_connection_verification_dialog.dart
frontend/lib/verification/scanner/verification_qr_content_parser.dart
frontend/lib/verification/verification_qr_scanner_page.dart

- fixed qr code verification scan
- adjusted connection error message
- added connection error dialog
resolves https://github.com/digitalfabrik/entitlementcard/issues/676

676: no internet verification

---

frontend/build-configs/bayern/index.ts
frontend/lib/about/about_page.dart
frontend/lib/about/content_tile.dart
frontend/lib/about/dev_settings_view.dart
frontend/lib/about/license_page.dart
frontend/lib/home/home_page.dart
frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
frontend/lib/identification/card_detail_view/card_detail_view.dart
frontend/lib/identification/card_detail_view/verification_code_view.dart
frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
frontend/lib/map/map/map.dart
frontend/lib/map/map_page.dart
frontend/lib/map/preview/accepting_store_preview_card.dart
frontend/lib/routing.dart
frontend/lib/search/filter_bar_button.dart
frontend/lib/search/search_page.dart
frontend/lib/store_widgets/detail/detail_app_bar.dart
frontend/lib/themes.dart
frontend/lib/widgets/app_bars.dart

This updates our app to use Material 3.
See https://docs.flutter.dev/development/ui/material3-updates for more details.
I simply adjusted a few paddings here and there to accomodate for the new design (and did some modest refactoring).
I also chose the more saturated EAK color even for light mode (as it is more saturated and the previous was almost not distinguishable from grey).

Use material 3 in flutter

---

administration/src/cards/extensions.tsx
specs/card.proto

Related to the discussion in #690

Use sint32 for birthday

---

administration/src/cards/CardBlueprint.ts
administration/src/components/cards/CreateCardForm.tsx

We decided to go for 50 bytes for the name.

690: Validate size of card blueprints

---

administration/src/project-configs/nuernberg/dataPrivacyBase.tsx

resolves https://github.com/digitalfabrik/entitlementcard/issues/733

733: Update data privacy nbg

---

frontend/build-configs/nuernberg/index.ts
frontend/lib/about/dev_settings_view.dart
frontend/lib/identification/id_card/card_content.dart

resolves https://github.com/digitalfabrik/entitlementcard/issues/525

525: Visualize birthday passnumber

---

.vscode/tasks.json
administration/src/cards/CardBlueprint.ts
administration/src/cards/PdfFactory.ts
administration/src/cards/activation.ts
administration/src/components/cards/CreateCardsController.tsx
frontend/lib/identification/activation_workflow/activation_code_scanner_page.dart
frontend/lib/identification/card_detail_view/verification_code_view.dart
frontend/lib/identification/qr_code_utils.dart
frontend/lib/identification/verification_workflow/query_server_verification.dart
frontend/lib/identification/verification_workflow/verification_qr_code_processor.dart
frontend/lib/identification/verification_workflow/verification_qr_scanner_page.dart
specs/card.proto

Not really imporntant ticket but had nothing to do 😅

720: rename verify to verification

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/nuernberg/steps/DownloadCsv.kt

Not sure how to reproduce the original issue though. Can someone please test this for me :)

762: Add encodeng to csv import

---

administration/src/cards/CardBlueprint.ts
administration/src/cards/cardBlueprints.ts
administration/src/cards/extensions.tsx
administration/src/components/cards/CreateCardForm.tsx

Extensions have not been applied properly.

Fix extensions in administration and make them more type safe

---

frontend/lib/map/map/map.dart
frontend/pubspec.lock
frontend/pubspec.yaml

This updates to a verion of maplibre flutter which includes https://github.com/m0nac0/flutter-maplibre-gl/pull/194
It also fixes the output of a strack trace in the console.
fixes #774

Fix map on android

---

frontend/build-configs/nuernberg/index.ts
frontend/lib/about/dev_settings_view.dart
frontend/lib/identification/id_card/card_content.dart

If a region extension is defined for a card in nuernberg, the title of the region ("Stadt Nürnberg") was shown at the top left of the card, instead of the specified title "Amt für ...".

Don't show region for nuernberg

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/constants.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/webservice/schema/RegionsQueryService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/webservice/schema/AcceptingStoreQueryService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardQueryService.kt
specs/backend-api.graphql

Revert: https://github.com/digitalfabrik/entitlementcard/pull/573
We want to get rid of the ehernamtskarte.app server. So let's support the old api.

Readd deprecated API

---

frontend/lib/about/dev_settings_view.dart

resolves https://github.com/digitalfabrik/entitlementcard/issues/805

805: change sample card name

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Schema.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/Setup.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/Application.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/BlueCardEntitlement.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/GoldenCardEntitlement.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/Organization.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/view/ApplicationVerificationView.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationVerificationsHolder.kt

Extract application verifications from GraphQL interface and write into DB

---

frontend/lib/identification/id_card/id_card.dart

840: Ignore text scale factor for card layout

---

administration/src/application/components/primitive-inputs/DateForm.tsx

Fixes: 
* User can enter a date earlier than 1900. (even earlier than 999) :D

Improve date validation

---

administration/src/ErrorHandler.tsx
administration/src/application/components/forms/RegionForm.tsx
administration/src/application/components/forms/StepSendForm.tsx
administration/src/application/components/primitive-inputs/SelectForm.tsx
administration/src/util/usePrevious.ts

@f1sh1918 : i've put together some minor adjustments for the form. Mostly minor stuff (adjusting some labels, small refactorings, avoiding/reducing some minor glitches)

624: Minor form adjustments

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/utils/PostalCodesLoader.kt

Looks like you can not use `File()` for internal resources instead we have to use `InputStream`
https://coderanch.com/t/750338/java/URI-hierarchical-DropBox-Upload-Code -> second post
resolves https://github.com/digitalfabrik/entitlementcard/issues/854

854: Fix uri not hierarchical

---

docs/postal-code-region-assigment.md

resolves https://github.com/digitalfabrik/entitlementcard/issues/847

847: add documentation for postal code region assigment

---

administration/src/Router.tsx
administration/src/application-verification/VerificationController.tsx
administration/src/components/applications/ApplicationsOverview.tsx
administration/src/graphql/applications/getApplication.graphql
administration/src/graphql/applications/verifyOrRejectApplication.graphql
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationQueryService.kt
specs/backend-api.graphql

I think technically the main functionality has been implemented. 
What's still missing is 
which I'd prefer to implement in separate PRs, as this one already feels quite bloated.
[EDIT] It feels like forever that I've implemented some UI. Feel free to be harsh 😀

837: verification view for applications

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt

resolves https://github.com/digitalfabrik/entitlementcard/issues/879

879: Send mail to applicant

---

administration/src/application-verification/VerificationController.tsx
administration/src/graphql/applications/getApplication.graphql

resolves https://github.com/digitalfabrik/entitlementcard/issues/869

869: Withdraw check verification overview

---

administration/src/KeepAliveToken.tsx
administration/src/components/Navigation.tsx

resolves https://github.com/digitalfabrik/entitlementcard/issues/883

883: logout redirect

---

administration/src/components/auth/Login.tsx

resolves https://github.com/digitalfabrik/entitlementcard/issues/918

918: Fix project switch

---

frontend/build-configs/bayern/index.ts

resolves https://github.com/digitalfabrik/entitlementcard/issues/898
wait for #888

898: Activate verification in app for bayern

---

administration/src/cards/cardBlueprints.ts

resolves https://github.com/digitalfabrik/entitlementcard/issues/925

925: Increase standard expiration period etc

---

administration/src/project-configs/ProjectConfigContext.tsx
administration/src/project-configs/getProjectConfig.ts

resolves https://github.com/digitalfabrik/entitlementcard/issues/920

920: Staging projectId

---

frontend/pubspec.lock
frontend/pubspec.yaml

This needs testing (only the scanner screen) on Android and iOS.

Upgrade mobile scanner to 3.1.1

---

administration/src/mui-modules/application/forms/ApplicationForm.tsx
administration/src/mui-modules/application/forms/StepCardTypeForm.tsx
administration/src/mui-modules/application/util/FormType.ts
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/Application.kt
specs/backend-api.graphql

894: Add physical card checkbox

---

administration/src/bp-modules/users/RoleHelpButton.tsx

941: update role info

---

docs/production-setup.md

927: Backend deployment docs

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ViewAdministratorsQueryService.kt

981: Show project admins

---

administration/src/cards/extensions/AddressFieldExtensons.ts

set initial state for address extensions

---

administration/package-lock.json
administration/package.json
administration/src/bp-modules/cards/AddCardForm.tsx
administration/src/cards/CardBlueprint.ts
administration/src/cards/extensions/BirthdayExtension.tsx

- replace `DateInput` by MUI `TextField`
Testing:
Create cards for nbg and bavaria with new datepicker
resolves #1003

1003: Datepicker shows wrong date

---

administration/.env.development
administration/.env.production
administration/src/bp-modules/NavigationBar.tsx

Since we had some caching problems with the customer, its nice to see the version info directly
resolves #1012

1012: Add version info

---

docs/production-setup.md
scripts/pack_deb.sh

added a postinst step in the debian packaging to run migration after upgrading
resolves #996

996: Migrate db postinst

---

docs/production-setup.md
scripts/pack_deb.sh

run post install only when packaging administration, before it ran on every package installation

996: Migrate db post install fix

---

.idea/kotlinc.xml
backend/build.gradle.kts
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/GeometryColumnType.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/database/repos/AcceptingStoresRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/steps/Store.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/common/steps/SanitizeGeocode.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/nuernberg/steps/Store.kt

There should be no breaking changes.

Upgrade backend dependencies

---

administration/src/bp-modules/cards/ImportCardsTable.tsx
administration/src/cards/CardBlueprint.ts

1022: Name length special chars

---

administration/src/mui-modules/application/forms/RegionForm.tsx

use correct link to old application forms

Fix application form link

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt

1042: Fix typo

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/Application.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/OrganizationContact.kt

There were some checks missing in the backend for required checkboxes. The application frontend does have the appropriate validation for those.

Add missing backend checks for required checkboxes

---

administration/resources/cards/sample-bulk-import-bayern.csv
administration/src/cards/extensions/BavariaCardTypeExtension.test.ts
administration/src/cards/extensions/BavariaCardTypeExtension.tsx

1043: Allow legacy blau and gold as card types

---

.circleci/config.yml

Any other files that might change unvoluntarily?

Fail CI when pubspec.lock changes

---

administration/src/mui-modules/application/forms/WorkAtOrganizationForm.tsx
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/WorkAtOrganization.kt

1062: Payment clarification

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardMutationService.kt

resolves #1066 
We can discuss what else should we log or if this is too much

1066: Log card activation

---

administration/src/errors/templates/InvalidLink.tsx

1102: Add hint when application deleted

---

.circleci/config.yml
scripts/eak-update.sh

resolves #1108
script was deployed and tested on staging server

1108: Prevent auto install entitlementcard

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/database/Schema.kt

Should fix migrations not working properly on main.

[fix]: add partial index for admin email

---

administration/src/mui-modules/application/forms/StepCardTypeForm.tsx

resolves #1044 
Note: Please ensure that the form data was deleted. If there is any form data in you local storage the change won't apply

1044: Only digital card default checked

---

administration/src/bp-modules/NavigationBar.tsx
administration/src/bp-modules/UserMenu.tsx

added a user menu and show some user information
I had to make the popover controlled since lot of things not working properly for the `Popover` component like backdrop.
I think we have to update to the new blueprint version at some point :)
resolves #975

975: Show more user information 

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/regions/database/EakBayernRegions.kt

resolves #1123
```sql
insert into regions values (<lastID>, 1, '09780','https://ehrenamtskarte.bayern.de','Oberallgäu','Landkreis', null, false);
```

1123: Add oberallgaeu

---

administration/src/mui-modules/application/forms/WorkAtOrganizationForm.tsx

Changed wording of heading and changed order as suggested in the ticket
Fixes: #1190

1190: Increase comprehensibility of application form

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/GraphQLExceptionHandler.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/matomo/Matomo.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/Importer.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/steps/DownloadLbe.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/steps/FilterLbe.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/steps/MapFromLbe.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/common/steps/SanitizeAddress.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/common/steps/Store.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/nuernberg/steps/DownloadCsv.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/nuernberg/steps/FilterGeoData.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/nuernberg/steps/MapFromCsv.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/pipelines/Importer.kt

@svenseeberg requested that we should change the log level of errors to errors to improve filtering out error messages in the live system.
- log all thrown (and logged) exceptions on error level
Fixes: #1128

1128: log errors as errors

---

administration/resources/cards/sample-bulk-import-bayern.csv

fix wrong headline

---

.circleci/config.yml
.circleci/src/workflows/backend.yml
.circleci/src/workflows/frontend.yml
CHANGELOG.md
administration/package.json
administration/src/bp-modules/cards/ImportCardsInput.tsx
administration/src/cards/hashCardInfo.test.ts
docs/production-setup.md
frontend/build-configs/nuernberg/index.ts
frontend/pubspec.yaml

https://github.com/digitalfabrik/entitlementcard/releases/tag/v.3.2.2

Release 3.2.2

---

backend/src/main/resources/config/config.yml
docs/freinet-documentation.md

Update to new endpoint url for stores

1235: Replace store endpoint bavaria

---

frontend/pubspec.yaml

Sorry i just forgot to push the recent build number after publishing the last ios release and merged the release branch before
- update build number to the current one

release-3.2.3: update build number

---

.circleci/config.yml
.circleci/src/jobs/build_administration.yml
administration/config/env.ts
administration/config/webpack.config.ts
administration/package-lock.json
administration/package.json
administration/tsconfig.json
frontend/.gitignore
frontend/build-configs/package-lock.json
frontend/build-configs/package.json
frontend/build-configs/tsconfig.json

Build app before start. Check out the webpack plugin [here](ForkTsCheckerWebpackPlugin)

1242: Remove typechecking during build

---

.gitignore
package-lock.json
package.json

This adds npm workspaces to ensure that build-configs are linked properly to administration, as without this, symlinking did not reliably for everyone.
- added a root package.json which defines admisistration and frontend/build-configs as packages

Use npm workspaces for proper linking

---

.circleci/config.yml
.circleci/src/jobs/bump_version.yml
.circleci/src/workflows/delivery_beta_native.yml
administration/package.json
frontend/pubspec.yaml
version.json

Versioning is automatically handled.
- Added entitlementcards to deliverino repos
- Adjusted toolbelt to allow version commits on all branches, see PR here: 
https://github.com/digitalfabrik/app-toolbelt/pull/2
- adjusted bump_verison step
- verison file should be used for frontend and administration
Fixes: #1164

1164: Handle versioning

---

.circleci/config.yml
.circleci/src/jobs/build_android.yml
.circleci/src/workflows/delivery_beta_native.yml
frontend/android/fastlane/Fastfile
version.json

apks are build and added to the artifacts tab
Fixes: #1263

Readd apks

---

.circleci/config.yml
.circleci/src/@common.yml
.circleci/src/jobs/promote_android.yml
.circleci/src/workflows/promote_native.yml
frontend/android/fastlane/Fastfile

Added the promote android job
Fixes: #1156

1156: Promote android

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/auth/webservice/schema/ResetPasswordMutationService.kt

I could not reproduce the issue apparently. But it seems it couldn't find the Project (when looking at the line number). Therefore, I added a check whether the project exists.
- check whether project exists
- don't send the reset mail if the administrator user cannot be found (this would only happen if you call the endpoint directly, I guess, but helps avoiding email scraping)
Fixes: #821

821: add sanity check for project on password reset

---

administration/src/mui-modules/application/forms/RegionForm.tsx
administration/src/mui-modules/application/forms/StepCardTypeForm.tsx

The are still old not working links in the submission form that have to be replaced.
- change region list link
- change requirement link
Fixes: #1302

1302: Change links submission forms

---

administration/resources/cards/sample-bulk-import-bayern.csv

The bulk import csv contained invalid content
- fix csv content to be valid

Fix bulk csv bavaria

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0008_IncreaseAdministratorEmailLength.kt

The format issues of the migration file caused klint to cause errors in gradle build
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4420/workflows/a589ac06-819c-454d-b57e-acf57768f564/jobs/34799
- adjust format

fix-v0008-migration-format

---

.circleci/config.yml
.circleci/src/jobs/check_backend.yml

On every commit it should be checked if the backend code is formatted properly
- add klint check to `check_backend`
Fixes: #1309

1309: Add klint check backend

---

.idea/runConfigurations/Test_administration.xml

try to fix conflicts by readding runConfig file
- readd runConfig

Fix readd administration test

---

docs/card-lifecycle.md

I added a short explanation of the card encodings. Further explanaitons might be found here -> https://nextcloud.tuerantuer.org/index.php/apps/files/files/884455?dir=/Projects/Digitale%20Berechtigungskarte/Pr%C3%A4sentationen
- document cardInfoHash
- document QR-Code encoding

Document card encodings

---

frontend/assets/l10n/app_de.json
frontend/assets/l10n/app_en.json
frontend/lib/about/about_page.dart

Added accessibility policy
Fixes: #1344

1344: Add accessibility policy

---

.circleci/config.yml
.circleci/src/commands/notify.yml
.circleci/src/jobs/build_martin.yml
.circleci/src/jobs/bump_version.yml
.circleci/src/jobs/check.yml
.circleci/src/jobs/check_health_backend.yml
.circleci/src/jobs/deliver_ios.yml
.circleci/src/jobs/deliver_to_server.yml
.circleci/src/jobs/pack_administration.yml
.circleci/src/jobs/pack_martin.yml
.circleci/src/jobs/pack_meta.yml
.circleci/src/jobs/promote_android.yml
.circleci/src/jobs/promote_to_server.yml

Fixed the failing jobs on commit_main workflow
- Adjusted some images
- unified checkout step
- installed npm and node where needed
See succeeded pipeline here:https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/4868/workflows/4a6c2141-747e-4370-a8eb-e0c14e4b786f
Fixes: #1350

1350: Fix failing main

---

docs/development-setup.md
frontend/README.md

Add small clarifications to the installation guide that will hopefully be helpful to "first-time-with-flutter" (and "first-time-with-protobuf") people
- add some detail
- use bullet points instead of nested numbered lists (1.1, 1.2, etc) because the latter are not supported in markdown
No (only docs affected)
Fixes: #

Update the installation guide

---

.circleci/config.yml
.circleci/src/commands/notify.yml
.circleci/src/jobs/deliver_to_server.yml
version.json

New beta release for administration and backend with small CD fixes.

Release 2024.3.16

---

administration/src/bp-modules/applications/ApplicationCard.tsx
administration/src/bp-modules/applications/JsonFieldArray.tsx
administration/src/bp-modules/applications/JsonFieldElemental.tsx

Improved hacky workaround for printing collapsed items :D
Fixes: #1377

1374: Fix printing glitch

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user-story.md

Just unified the templates a little with Integreat and adjusted to the new renamed labels.

Unify issue template with Integreat and new labels

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/application/database/repos/ApplicationRepository.kt

Forgot to remove not needed function that i creating during #1206 
Also found a second function that is unused
- remove `findVerificationsByIds`
- remove `getApplicationById`

Cleanup fkt backend

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/mail/Mailer.kt
docs/development-setup.md

Change the text of the approval mail for volunteers
- mail adjustment
- fix the emoji in the dev setup doc
- probably no
Fixes: #1205

1205: Change the text of the approval mail for volunteers

---

.circleci/config.yml
.circleci/src/jobs/promote_to_server.yml

node & npm has to be installed before app-toolbelt

1157: Fix promote to server

---

docs/sozialpass-stores-import.md

File in nextcloud changes to csv. docs had to be updated

Update store import docs

---

administration/src/errors/DefaultErrorMap.tsx
administration/src/errors/templates/InvalidLink.tsx
administration/src/mui-modules/application/forms/OrganizationForm.tsx
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/OrganizationContact.kt

Small text adjustments in the application form and in the invalid approval link
no?
Fixes: #1435
Fixes: #1404

1435 Fix typo in application form & 1404 Adjust text for invalid approval link

---

.circleci/config.yml
.circleci/src/@common.yml
.circleci/src/jobs/deliver_to_server.yml
.circleci/src/workflows/deliver_beta_all.yml
frontend/ios/fastlane/metadata/bayern/release_notes.txt
frontend/ios/fastlane/metadata/nuernberg/release_notes.txt

Added beta all delivery workflow, so we have the versions of backend/administration and native in sync.
Fixes: #1363

1363: Beta delivery workflow

---

backend/src/main/resources/graphiql/index.html
backend/src/main/resources/graphiql/renderExample.js

This updates the version of GraphiQL (a visual / interactive API explorer available at https://api.entitlementcard.app/graphiql/  or localhost:8000/graphiql/).
I used the resources available at https://github.com/graphql/graphiql/tree/main/packages/graphiql/resources
None

Upgrade GraphiQL

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/common/utils/DateUtils.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/utils/TimeStampUtil.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/database/repos/CardRepository.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/webservice/schema/CardStatisticsQueryService.kt
specs/backend-api.graphql

* Use Instant instead of TimeStamp (as we use Instant everywhere)
* Properly convert to Instant by using the project time zone
* slightly adjust SQL query

Properly convert date string to instant using project timezone

---

.circleci/config.yml
.circleci/src/jobs/check_health_backend.yml
administration/src/bp-modules/statistics/__tests__/CSVStatistics.test.ts

- add sudo for backend package postinstall
- fix tsc build: looks like due to merging issues some prop in a test was lost

Fix check backend health

---

version.json

Release 2024.6.1

---

version.json

Urgent backend fix included
-
-
-
-
Fixes: #

release-2024.6.2

---

docs/sozialpass-stores-import.md

Updated the docs and updated the stores (other repo)
Fixes: #1488

1488: Update store data nbg

---

frontend/build-configs/bayern/index.ts
frontend/build-configs/nuernberg/index.ts
frontend/build-configs/types.ts
frontend/lib/home/home_page.dart
frontend/lib/store_widgets/detail/detail_app_bar.dart

We would like to disable favorites feature, until https://github.com/digitalfabrik/entitlementcard/issues/1493 is fixed
Add a feature flag for Favorites in build configuration
No?
Fixes: #1523

1523: Add feature flag to disable favorites in the configuration

---

administration/src/mui-modules/application/forms/OrganizationForm.tsx
administration/src/mui-modules/application/forms/StepSendForm.tsx
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/ApplicationDetails.kt

Change warning text in the application form when the applicant and the approver are identical
no?
Fixes: #1530
Fixes: #1490

1530: Change warning text in the application form

---

frontend/assets/nuernberg/l10n/override_de.json

Fix typo for invalid pass.
Fix typo.
None.
Fixes: #1529.

1529: Fix typo

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/matomo/Matomo.kt

Previously the new tracker was never persisted. So new trackers were created with every request.
Fixes an issue in https://github.com/digitalfabrik/entitlementcard/pull/1546

Fix matomo tracker singleton

---

.github/hooks/pre-commit

Added react linting to pre commit hook.

Add react lint check to pre commit

---

frontend/android/settings.gradle

This issue was reported from the play store even i couldn't reproduce any crash.
- update android sdk version
- none
Fixes: #1471 
- build and start the app on android

1471: Update android sdk

---

.github/PULL_REQUEST_TEMPLATE.md

Add testing information to PR template.
Add testing information to PR template.
None.
Fixes: None.

Add testing information to PR template

---

backend/build.gradle.kts
backend/src/test/kotlin/app/ehrenamtskarte/backend/IntegrationTest.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/cards/CreateCardFromSelfServiceTest.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/ExampleCards.kt
backend/src/test/resources/config.test.yml

Tests for #1421
Just tests
Fixes: #1568

1568: Add tests for createCardFromSelfService mutation

---

frontend/ios/fastlane/Fastfile

Fix metadata path

---

.circleci/config.yml
.circleci/src/workflows/deliver_beta_backend_administration.yml
.circleci/src/workflows/deliver_production_backend_administration.yml
.circleci/src/workflows/delivery_production_native.yml

Add notify release to missing workflows
- add to missing beta workflows
- add to missing production workflows
- none
Fixes: #1585

1585: Notify release backend

---

version.json

Had to update `version.json` since last hotfix release wasn't properly merged

release-2024.8.1

---

.circleci/config.yml
.circleci/src/jobs/check_administration.yml
administration/package.json

- adjusted test task to also create coverage report
- store coverage report
Reports can be checked here f.e.
https://output.circle-artifacts.com/output/job/6bf3cd82-a98f-4ed5-b7a4-dcbf403b3211/artifacts/0/~/attached_workspace/coverage/lcov-report/index.html
`npm run test:coverage`
looks like 63% of lines are covered.

Administration test coverage report

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/steps/DownloadLbe.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/stores/importer/bayern/types/LbeAcceptingStore.kt
version.json

Fixes #1641 
- Adds a missing field to the Jackson object.
- Disables failing on unknown fields.
- Tested locally
Fixes: #1641

Fix import of stores

---

backend/build.gradle.kts

Update some backend dependencies that might have vulnerabilities.
Also revert the wrong fix for #1509, #1544

Update potentially vulnerable backend dependencies

---

administration/src/project-configs/koblenz/dataPrivacyBase.tsx

As a user i want to be informed about data privacy
- add data privacy text as react element
- none
1. http://localhost:3000/data-privacy-policy
2. check for spelling and style issues. check links and working mail addresses. Source file is linked in the issue
Fixes: #1545

1545: Provide data privacy text

---

frontend/lib/activation/deeplink_activation.dart
frontend/lib/identification/card_detail_view/card_detail_view.dart
frontend/lib/identification/id_card/id_card_with_region_query.dart
frontend/lib/identification/verification_workflow/dialogs/positive_verification_result_dialog.dart
frontend/lib/identification/verification_workflow/dialogs/remove_card_confirmation_dialog.dart

Extract widget for id card with automatic fetching of the region.
The region query was previously always added when using IdCard.
This change simply extracts this wrapper into its own widget, and therefore removes some code duplication (and some indenting).
No
Check out the Ausweisen tab as a reference. For very eager testers: Also check whether the IdCard is displayed for Nürnberg Pass.

Extract widget for id card with region query

---

frontend/ios/Podfile.lock
frontend/ios/Runner.xcodeproj/project.pbxproj
frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Bayern.xcscheme
frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/Nuernberg.xcscheme
frontend/ios/Runner.xcodeproj/xcshareddata/xcschemes/ScreenshotTests.xcscheme
frontend/pubspec.lock
frontend/pubspec.yaml

Adujsted project so it builds on Xcode 16
Updated sentry to fix this: https://github.com/getsentry/sentry-react-native/issues/3883
Updated url launcher to fix this https://github.com/flutter/flutter/issues/152986
- May break anything related to any library
smoke test the whole app on iOS and android
check if the app builds on Xcode 16 and 15 for you please
no issue, but will me merged into / is needed for #1431

Updates to support xcode 16

---

frontend/lib/configuration/settings_model.dart
frontend/lib/home/home_page.dart
frontend/lib/intro_slides/location_request_button.dart
frontend/lib/location/determine_position.dart
frontend/lib/map/floating_action_map_bar.dart
frontend/lib/map/location_button.dart
frontend/lib/map/map/map.dart
frontend/lib/map/map/map_with_futures.dart
frontend/lib/map/map_page.dart
frontend/lib/search/search_page.dart
frontend/lib/search/sorting_button.dart

Correctly display the location status on the location button and add new follow user icon.
- Extract LocationIcon component to correctly display status
- Add state to home_page to control the user follow mode
- Remove redundant locationFeatureEnabled setting (controlled by permission now)
- Remove onFeatureEnable and onFeatureDisable settings
None.
- Test the location button in various settings (permissions granted, forbidden, ...)
- Move the map and recenter again
- Test the sorting button in various settings (permissions granted, forbidden, ...)
Fixes: #1474.

1474: Correctly display the location status on the location button

---

administration/src/bp-modules/cards/AddCardsForm.tsx
administration/src/bp-modules/cards/ImportCardsController.tsx
administration/src/bp-modules/cards/ImportCardsInput.tsx

added some renames @steffenkleinle

1666: Rename missing variables

---

.idea/runConfigurations/Set_build_config_bayern.xml
.idea/runConfigurations/Set_build_config_bayern_floss.xml
.idea/runConfigurations/Set_build_config_koblenz.xml
.idea/runConfigurations/Set_build_config_nuernberg.xml

`flutter pub run` is deprecated in favor of `dart run`

Use dart run instead of flutter pub run

---

frontend/ios/ScreenshotTests/ScreenshotTests.swift
frontend/ios/fastlane/README.md
frontend/ios/fastlane/Snapfile
frontend/ios/fastlane/SnapshotHelper.swift

As a user i want to have recent screenshots in the app stores
- added screenshots for the different device sizes to appstore connect and play console
- appstore connect: https://appstoreconnect.apple.com/apps/6670392532/distribution/ios/version/inflight
- play console: https://play.google.com/console/u/0/developers/5269030016285360668/app/4975896453049363426/main-store-listing
- also updated device list for ios snapshot tests to have more recent ones that work with current ios version
- updated fastlane snap
- fixed snapshot tests to work with recent xcode version
- added testcase for detail view koblenz
- none
Check store entries and run snapshot tests for ios (check readme.md)
Fixes: #1698

1698: Update screenshots

---

backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationService.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/schema/create/WorkAtOrganization.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationHandler.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/application/webservice/EakApplicationMutationServiceTest.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestApplicationBuilder.kt
specs/backend-api.graphql

Added option to set isVerifiedApplication flag when calling addEak mutation
- adjusted eak mutation
- added tests
- May break the standart application creation from `/beantragen`
Call mutation with and without flag.
Fixes: #1621

1621: Adjust application endpoint for verein360

---

administration/src/bp-modules/self-service/hooks/useCardGeneratorSelfService.tsx

Fix query params in the create card form
P.S. CI is failing with the same error btw
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/6968/workflows/f5f63472-e4ee-4df2-a828-b98f75cdd26b/jobs/48228?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
no
The link should work and fill the form:
localhost:3000/erstellen?Name=Karla%20Koblenz&Referenznummer=123K&Geburtsdatum=10.06.2003

1430: Fix query params in the create card form

---

administration/src/mui-modules/application/forms/OrganizationForm.tsx

Fix email translation key
no
check eak application form http://localhost:3000/beantragen
n/a

Fix email translation in the application form

---

version.json

release-2024.12.0: update version

---

administration/src/bp-modules/cards/hooks/useCardGenerator.ts

Add prefix to filename as this breaks automation on nuernberg side
Fixes: #1833

1833: Fix filename for nuernberg

---

docs/verein360-enpoint.md

Adjust verein 360 docs

---

version.json

New version including last bug fixes for koblenz and everything for verein360
edit: sorry i messed up here a bit, so version 2024.12.1 is now skipped.

update version for next release

---

.circleci/config.yml
.circleci/src/jobs/check_frontend.yml
frontend/.gitignore
frontend/ios/Podfile.lock
frontend/lib/identification/card_detail_view/card_carousel.dart
frontend/lib/identification/identification_page.dart
frontend/lib/identification/verification_workflow/dialogs/remove_card_confirmation_dialog.dart
frontend/lib/main.dart
frontend/pubspec.lock
frontend/pubspec.yaml

Upgrades pubs that are easy to upgrade.
The replacement of artemis (PR incoming) is a bit more involved (but still not outrageous in size). Therefore, I made it in a separate PR.
Hopefully none.
Some smoke testing.

Upgrade some pubs

---

administration/src/util/translations/de.json
backend/src/main/kotlin/app/ehrenamtskarte/backend/application/webservice/utils/ApplicationHandler.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/common/webservice/CustomDataFetcherExceptionHandler.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/exception/GraphQLBaseException.kt
backend/src/main/kotlin/app/ehrenamtskarte/backend/exception/webservice/exceptions/InvalidJsonException.kt

Currently, sending invalid requests to an application endpoint results in 500 server errors, and no error description provided to the user.
This happens because we do validation in init blocks of the data classes, and the exceptions that occur get wrapped up in InvocationTargetException, which are not handled.
- refactor CustomDataFetcherExceptionHandler to get rid of the deprecated function
- unwrap InvocationTargetException to return GraphQLBaseException to the user
No?
1. Login to administration as Verein360 admin, create API token
2. Send addEakApplication request using the created token
3. Set some invalid data in the request, for example, givenInformationIsCorrectAndComplete = false
4. Check error response
Valid request example:
```
mutation AddEakApplication {
addEakApplication( …
```

1816: Input validation for application endpoint

---

version.json

release-2025.1.0: update version

---

frontend/lib/main.dart

The error still occurred on ios, so i created a proposal how to fix it
- create an init translations function and await it it load
- await all async functions
- none
Fixes: #

1882: Fix load translations ios proposal

---

administration/src/bp-modules/self-service/__tests__/CardSelfServiceForm.test.tsx

fixes the unit test by providing correct project config

Fix self service form test

---

CODEOWNERS

Update `CODEOWNERS` file:
- Remove @ztefanie 
- Add @andrew8er, @bahaaTuffaha
-
- None
N/A
Fixes: #1937

1937: Update `CODEOWNERS`

---

.circleci/config.yml
.circleci/src/jobs/notify_release.yml

Update release notification messages:
- Add `Sozialpass Koblenz`
-
N/A
N/A
Fixes: #1861

Update release notification messages

---

version.json

Release 2025.2.0

---

README.md
docs/conventions.md

Add docs about conventions.
N/A
N/A
Fixes: N/A

Add docs about conventions

---

frontend/ios/Podfile.lock

Upgrade frontend/ios dependencies
- Sentry/HybridSDK
- MapLibre
-
-
Fixes: https://github.com/digitalfabrik/entitlementcard/pull/1992#pullrequestreview-2694457482

Upgrade frontend/ios dependencies

---

version.json

release-2025.3.2

---

.circleci/config.yml
.circleci/src/jobs/promote_android.yml
.circleci/src/jobs/promote_ios.yml
.circleci/src/workflows/delivery_production_frontend.yml
.circleci/src/workflows/promotion_all.yml
.circleci/src/workflows/promotion_frontend.yml
frontend/ios/fastlane/koblenz/metadata/de-DE/release_notes.txt

Add koblenz to production delivery and promotion.
- Add koblenz to production delivery and promotion
- Fix ios upload by adding release note
N/A
N/A
Fixes: #1427

1427: Add koblenz to production delivery and promotion

---

.circleci/config.yml
.circleci/src/jobs/promote_github_release.yml
.circleci/src/jobs/promote_server.yml
scripts/notify-mattermost
version.json

Fix notify by checking out project in every job.
- Fix notify by checking out project in every job.
N/A
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/7830/workflows/3d89fbb6-9f77-4a0d-bd5a-dc4b0fd64b18/jobs/53368
Fixes: #2027

2027: Fix notify by checking out notify script

---

administration/src/cards/extensions/__tests__/BirthdayExtension.test.tsx

Add unit tests for birthday extensions
- add tests for component and functions of the extension
- none
N/A
Fixes: #1951

1951: Birthday extension test

---

package-lock.json
package.json

Changed App-toolbelt to version 0.4.0
- Changed App-toolbelt to version 0.4.0
Hope none.
N/A
Fixes: #2067

2067: Update app-toolbelt to version 0.4.0

---

.github/dependabot.yaml

Fix dependabot config by adding schedules.
See https://github.com/digitalfabrik/entitlementcard/runs/41264273757

1907: Add schedules to dependabot config

---

docker/nginx-development.conf

Adjusts the nginx rewrite (see issue description).
Fixes: #1997

1997: Adjust nginx rewrite

---

docs/troubleshooting.md

Updating our knowledge base on a recently explored issue: eak import stores failure
- update docs
no
n/a
n/a

Add troubleshooting info on eak stores import failure

---

backend/build.gradle.kts
docs/development-setup.md

Add more details to the setup documentation and recommend podman over docker.
N/A
N/A
Fixes: N/A

Add setup documentation

---

README.md
docs/backend-first-steps.md
docs/working-with-graphql-api.md

To get a better onboarding for newcomers, i provided some first steps for backend development.
- added some documentation about how to create a simple graphql query and use it in the frontend
- none
N/A

Docs backend first steps

---

package-lock.json
package.json

Bump app-toolbelt and ensure versioning still works.
- Bump the app-toolbelt to v0.5.2 including https://github.com/digitalfabrik/app-toolbelt/pull/33
N/A
No testing needed, just see that the CI still works fine: 
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8300/workflows/c3168b66-622a-4513-8525-feb5ba102252
Fixes: N/A

Bump app-toolbelt

---

administration/config/babel-dependencies.config.ts

I messed up when simplifying #2219 before merging, resulting in the build failing on the main branch.
So here's the fix :D
(It's a bit unfortunate, that the production bundle is not built on commit I think)

Fix babel config

---

backend/src/test/kotlin/app/ehrenamtskarte/backend/GraphqlApiTest.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/IntegrationTest.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestAdministrators.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/helper/TestFreinetAgencies.kt
backend/src/test/kotlin/app/ehrenamtskarte/backend/userdata/UserImportTest.kt

Our backend tests became slower after some dependency updates.
Suggested changes allow to speed up tests by half.
Main:
Current branch:
- Use singleton database container. This saves time because the container is not restarted and migrations are not reapplied between tests
- Move graphql handler creation for tests to the static context
no
Dev only:
Tests can be run locally using "Test backend" run configuration
Fixes: #2268

2268: Optimize backend tests performance

---

backend/build.gradle.kts
backend/gradle/libs.versions.toml

Update sentry to recent version
- update plugin version
- add required task dependencies for build and testing
- none
1. Test if build and test works (backend folder)
Token: https://passbolt.tuerantuer.org/app/passwords/view/9aa6c68e-3d03-4dc4-9152-bdc4bdc24f0e
```
SENTRY_AUTH_TOKEN=<token> ./gradlew build -Denv=prod
```
2. Test if errors will still be send to sentry, find steps there: (https://github.com/digitalfabrik/entitlementcard/pull/2209)
3. Please remove the errors from sentry by selecting the error and  using (... -> Delete)
Fixes: #2284

2284: Update sentry

---

frontend/ios/Podfile.lock

Fix failed build
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/8863/workflows/3f1b8fb2-0b61-412e-8b26-aa337b47a87b/jobs/57812?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
Update pod file
no?
Fixed build
https://github.com/digitalfabrik/entitlementcard/runs/45561472061
n/a

Fix build ios job

---

administration/src/bp-modules/cards/AddCardsForm.tsx

Misaligned card creation form.
- Used flex-wrap instead and justify-content for scrollable.
- None.
- Go to card creation and test the adding how it behaves. http://localhost:3000/cards/add
Fixes: #2318

2318: Center card creation form

---

administration/src/project-configs/bayern/config.ts

Enable freinet data transfer
- enable freinet data transfer for production
There is nothing additional to test. All testing happened in the related freinet issues
Fixes: #2360

2360: Enable freinet data transfer

---

.github/workflows/jest-test-coverage.yaml

As a dev i might want to see the code coverage on each pull request
- add jest code coverage workflow
- none
Fixes partly: #1682
I used this documentation:
https://github.com/marketplace/actions/jest-coverage-report

1682: Code coverage jest

---

administration/src/mui-modules/application-verification/ApplicationVerificationController.tsx
administration/src/util/translations/de.json

- remove hint for verifiers, when application was already processed
- none
- Create an application
- Process an application (Reject/approve)
- Check the verification link
Fixes: #2461

2461: Remove hint

---

docs/conventions.md

- add pull request sections
- add a labels section to conventions.md and refer to it
- none
Fixes: #

Docs conventions labels

---

docs/development-setup.md
docs/migrations.md

Changed command `docker-compose` to state-of-the-art command `docker compose` in the documentation markdown files.
- None
- No resolved issue, but keeping docs up-to-date

doc-development-setup

---

version.json

release-2025.9.3: update version code
